// Generated by vcv/tools/make-plugin.js. One generic module; each bank in bank.hpp is its own model.
#include "plugin.hpp"
#include "bank.hpp"

// 0 V is the item's From setting in the app, 10 V its To. Values go out as MIDI CC when they change.
// Every module remembers the MIDI device last chosen on any Curiosities module, so a new one is ready to go.
static json_t* lastMidiJ = NULL;

static const NVGcolor LEVEL_COLORS[4] = {
  nvgRGB(0xc4, 0x47, 0x2f), // curiosity
  nvgRGB(0xc9, 0x8a, 0x14), // suite
  nvgRGB(0x2f, 0x7f, 0x78), // proximity
  nvgRGB(0x5d, 0x4f, 0xa8), // proximity suite
};

// ---------- OSC over UDP to the desktop app's bridge (127.0.0.1:7000), the second way out besides MIDI ----------
// Address /curio/set/<level>/<id> with one float 0..1, as in the desktop bridge (apps/curiosities/desktop/README.md).
#if defined(ARCH_WIN)
  #include <winsock2.h>
  #include <ws2tcpip.h>
  typedef SOCKET curio_socket;
  #define CURIO_BAD_SOCKET INVALID_SOCKET
#else
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <arpa/inet.h>
  #include <unistd.h>
  typedef int curio_socket;
  #define CURIO_BAD_SOCKET (-1)
#endif
#include <cstring>

struct CurioOsc {
  curio_socket sock = CURIO_BAD_SOCKET;
  sockaddr_in addr;

  bool open() {
    if (sock != CURIO_BAD_SOCKET)
      return true;
#if defined(ARCH_WIN)
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif
    sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock == CURIO_BAD_SOCKET)
      return false;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(7000);
    addr.sin_addr.s_addr = htonl(0x7f000001); // 127.0.0.1
    return true;
  }

  static void pad(std::string& b) {
    do b.push_back('\0'); while (b.size() % 4);
  }

  // One OSC message with one big-endian int32 (",i").
  void sendInt(const std::string& address, int32_t v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",i";
    pad(b);
    uint32_t u = htonl((uint32_t) v);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }

  // One OSC message: the address, the type tag ",f", one big-endian float.
  void sendFloat(const std::string& address, float v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",f";
    pad(b);
    uint32_t u;
    std::memcpy(&u, &v, 4);
    u = htonl(u);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }
};
static CurioOsc curioOsc;

// "c:music" -> "/curio/set/c/music" (or "/curio/trigger/c/music")
static std::string oscAddress(const char* key, const char* verb = "set") {
  std::string k = key;
  size_t colon = k.find(':');
  if (colon == std::string::npos)
    return "";
  return std::string("/curio/") + verb + "/" + k.substr(0, colon) + "/" + k.substr(colon + 1);
}

struct CurioModule : Module {
  const CurioBank* bank;
  midi::Output midiOutput;
  int lastValues[16];
  float lastOsc[16];
  bool useOsc = false; // send OSC to the desktop app instead of MIDI
  bool gateOn[16] = {};
  dsp::ClockDivider sendDivider;
  dsp::ClockDivider rememberDivider;

  CurioModule(const CurioBank* b) : bank(b) {
    config(0, 32, 0, 0);
    for (int i = 0; i < 16; i++) {
      if (i < bank->count) {
        configInput(i, bank->jacks[i].label);
        configInput(16 + i, std::string(bank->jacks[i].label) + ": on/off gate (OSC)");
      }
      else {
        configInput(i, "Unused");
        configInput(16 + i, "Unused");
      }
    }
    sendDivider.setDivision(64);
    rememberDivider.setDivision(48000);
    onReset();
  }

  void onReset() override {
    for (int i = 0; i < 16; i++) {
      lastValues[i] = -1;
      lastOsc[i] = -1.f;
    }
    midiOutput.reset();
    if (lastMidiJ)
      midiOutput.fromJson(lastMidiJ);
    midiOutput.setChannel(bank->channel - 1);
  }

  void process(const ProcessArgs& args) override {
    if (rememberDivider.process()) {
      // Remember this module's device for the next one added.
      if (midiOutput.getDeviceId() >= 0) {
        if (lastMidiJ)
          json_decref(lastMidiJ);
        lastMidiJ = midiOutput.toJson();
      }
    }
    if (!sendDivider.process())
      return;
    if (useOsc && bank->jacks[0].key[0]) {
      // Gates switch the item on and off: /curio/trigger/<level>/<id> 1 on the rise, 0 on the fall.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[16 + i].isConnected())
          continue;
        bool high = inputs[16 + i].getVoltage() >= 1.f;
        if (high == gateOn[i])
          continue;
        gateOn[i] = high;
        curioOsc.sendInt(oscAddress(bank->jacks[i].key, "trigger"), high ? 1 : 0);
      }
      // OSC keeps fine steps: anything that moved by more than about 0.1% goes out.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[i].isConnected())
          continue;
        float m = clamp(inputs[i].getVoltage() / 10.f, 0.f, 1.f);
        if (std::fabs(m - lastOsc[i]) < 0.001f)
          continue;
        lastOsc[i] = m;
        curioOsc.sendFloat(oscAddress(bank->jacks[i].key), m);
      }
      return;
    }
    for (int i = 0; i < bank->count; i++) {
      if (!inputs[i].isConnected())
        continue;
      int v = (int) clamp(std::round(inputs[i].getVoltage() / 10.f * 127.f), 0.f, 127.f);
      if (v == lastValues[i])
        continue;
      lastValues[i] = v;
      midi::Message m;
      m.setStatus(0xb);
      m.setNote(bank->jacks[i].cc);
      m.setValue(v);
      midiOutput.sendMessage(m);
    }
  }

  json_t* dataToJson() override {
    json_t* rootJ = json_object();
    json_object_set_new(rootJ, "midi", midiOutput.toJson());
    json_object_set_new(rootJ, "osc", json_boolean(useOsc));
    return rootJ;
  }

  void dataFromJson(json_t* rootJ) override {
    json_t* midiJ = json_object_get(rootJ, "midi");
    if (midiJ)
      midiOutput.fromJson(midiJ);
    json_t* oscJ = json_object_get(rootJ, "osc");
    if (oscJ)
      useOsc = json_boolean_value(oscJ);
    // The channel belongs to the bank, whatever a saved patch says.
    midiOutput.setChannel(bank->channel - 1);
  }
};

// A name printed beside a jack, colored by level. SVG text does not render in Rack, so labels are drawn here.
struct CurioLabel : Widget {
  std::string text;
  NVGcolor color = nvgRGB(0x21, 0x1d, 0x1a);
  float fontSize = 9.f;

  void draw(const DrawArgs& args) override {
    std::shared_ptr<window::Font> font = APP->window->loadFont(asset::system("res/fonts/DejaVuSans.ttf"));
    if (!font || font->handle < 0)
      return;
    nvgFontFaceId(args.vg, font->handle);
    nvgFontSize(args.vg, fontSize);
    nvgFillColor(args.vg, color);
    nvgTextAlign(args.vg, NVG_ALIGN_LEFT | NVG_ALIGN_TOP);
    nvgTextLineHeight(args.vg, 1.05f);
    nvgTextBox(args.vg, 0, 0, box.size.x, text.c_str(), NULL);
  }
};

static CurioLabel* makeLabel(Vec pos, Vec size, std::string text, NVGcolor color, float fontSize) {
  CurioLabel* l = new CurioLabel;
  l->box.pos = pos;
  l->box.size = size;
  l->text = text;
  l->color = color;
  l->fontSize = fontSize;
  return l;
}

// Two columns of eight jacks, each with its name to the right.
static void addJacks(ModuleWidget* w, Module* module, const CurioBank* bank, int count, const char* const* names, const int* levels) {
  for (int i = 0; i < 16; i++) {
    int col = i / 8;
    int row = i % 8;
    float x = 6.f + col * 40.f;
    float y = 30.f + row * 12.f;
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, y)), module, i));
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x + 8.5f, y)), module, 16 + i));
    if (i < count)
      w->addChild(makeLabel(mm2px(Vec(x + 13.f, y - 4.2f)), mm2px(Vec(23.f, 9.f)), names[i], LEVEL_COLORS[levels[i]], 8.f));
  }
}

struct CurioWidget : ModuleWidget {
  const CurioBank* bank;

  CurioWidget(CurioModule* module, const CurioBank* b) : bank(b) {
    setModule(module);
    setPanel(createPanel(asset::plugin(pluginInstance, "res/Curio.svg")));
    addChild(makeLabel(mm2px(Vec(4.f, 6.f)), mm2px(Vec(73.28f, 8.f)), bank->title, nvgRGB(0x21, 0x1d, 0x1a), 14.f));
    addChild(makeLabel(mm2px(Vec(4.f, 14.f)), mm2px(Vec(73.28f, 8.f)),
      string::f("MIDI ch %d, CC %d-%d. Left jack: 0 V From, 10 V To. Right jack: on/off gate (OSC).", bank->channel, bank->jacks[0].cc, bank->jacks[bank->count - 1].cc),
      nvgRGB(0x6d, 0x65, 0x5d), 8.f));
    const char* names[16];
    int levels[16];
    for (int i = 0; i < 16; i++) {
      names[i] = i < bank->count ? bank->jacks[i].label : "";
      levels[i] = i < bank->count ? bank->jacks[i].level : 0;
    }
    addJacks(this, module, bank, bank->count, names, levels);
  }

  void appendContextMenu(Menu* menu) override {
    CurioModule* module = dynamic_cast<CurioModule*>(this->module);
    if (!module)
      return;
    menu->addChild(new MenuSeparator);
    if (bank->jacks[0].key[0])
      menu->addChild(createBoolPtrMenuItem("Send by OSC to the desktop app (port 7000)", "", &module->useOsc));
    menu->addChild(createMenuLabel("MIDI output (to the Curiosities app in a browser)"));
    appendMidiMenu(menu, &module->midiOutput);
  }
};

// Each bank is its own model: a module and widget type fixed to one entry of CURIO_BANKS.
template <int N>
struct BankModule : CurioModule {
  BankModule() : CurioModule(&CURIO_BANKS[N]) {}
};
template <int N>
struct BankWidget : CurioWidget {
  BankWidget(BankModule<N>* module) : CurioWidget(module, &CURIO_BANKS[N]) {}
};

Model* curioModels[] = {
  createModel<BankModule<0>, BankWidget<0>>("Curio-camera-angle-1"),
  createModel<BankModule<1>, BankWidget<1>>("Curio-camera-angle-2"),
  createModel<BankModule<2>, BankWidget<2>>("Curio-camera-motion-1"),
  createModel<BankModule<3>, BankWidget<3>>("Curio-camera-motion-2"),
  createModel<BankModule<4>, BankWidget<4>>("Curio-character-motion-1"),
  createModel<BankModule<5>, BankWidget<5>>("Curio-character-motion-2"),
  createModel<BankModule<6>, BankWidget<6>>("Curio-placement"),
  createModel<BankModule<7>, BankWidget<7>>("Curio-lines-1"),
  createModel<BankModule<8>, BankWidget<8>>("Curio-lines-2"),
  createModel<BankModule<9>, BankWidget<9>>("Curio-movement-lines"),
  createModel<BankModule<10>, BankWidget<10>>("Curio-background"),
  createModel<BankModule<11>, BankWidget<11>>("Curio-light-1"),
  createModel<BankModule<12>, BankWidget<12>>("Curio-light-2"),
  createModel<BankModule<13>, BankWidget<13>>("Curio-light-3"),
  createModel<BankModule<14>, BankWidget<14>>("Curio-effects-1"),
  createModel<BankModule<15>, BankWidget<15>>("Curio-effects-2"),
  createModel<BankModule<16>, BankWidget<16>>("Curio-arc"),
  createModel<BankModule<17>, BankWidget<17>>("Curio-plot"),
  createModel<BankModule<18>, BankWidget<18>>("Curio-mindset"),
  createModel<BankModule<19>, BankWidget<19>>("Curio-focus"),
  createModel<BankModule<20>, BankWidget<20>>("Curio-archetype-1"),
  createModel<BankModule<21>, BankWidget<21>>("Curio-archetype-2"),
  createModel<BankModule<22>, BankWidget<22>>("Curio-archetype-3"),
  createModel<BankModule<23>, BankWidget<23>>("Curio-herd"),
  createModel<BankModule<24>, BankWidget<24>>("Curio-wardrobe-1"),
  createModel<BankModule<25>, BankWidget<25>>("Curio-wardrobe-2"),
  createModel<BankModule<26>, BankWidget<26>>("Curio-color-1"),
  createModel<BankModule<27>, BankWidget<27>>("Curio-color-2"),
  createModel<BankModule<28>, BankWidget<28>>("Curio-set-1"),
  createModel<BankModule<29>, BankWidget<29>>("Curio-set-2"),
  createModel<BankModule<30>, BankWidget<30>>("Curio-emotion-1"),
  createModel<BankModule<31>, BankWidget<31>>("Curio-emotion-2"),
  createModel<BankModule<32>, BankWidget<32>>("Curio-emotion-3"),
  createModel<BankModule<33>, BankWidget<33>>("Curio-emotion-4"),
  createModel<BankModule<34>, BankWidget<34>>("Curio-emotion-5"),
  createModel<BankModule<35>, BankWidget<35>>("Curio-emo-road"),
  createModel<BankModule<36>, BankWidget<36>>("Curio-comedy-1"),
  createModel<BankModule<37>, BankWidget<37>>("Curio-comedy-2"),
  createModel<BankModule<38>, BankWidget<38>>("Curio-comedy-3"),
  createModel<BankModule<39>, BankWidget<39>>("Curio-comedy-4"),
  createModel<BankModule<40>, BankWidget<40>>("Curio-comedy-5"),
  createModel<BankModule<41>, BankWidget<41>>("Curio-comedy-6"),
  createModel<BankModule<42>, BankWidget<42>>("Curio-comedy-mix"),
  createModel<BankModule<43>, BankWidget<43>>("Curio-music-1"),
  createModel<BankModule<44>, BankWidget<44>>("Curio-music-2"),
  createModel<BankModule<45>, BankWidget<45>>("Curio-structure-1"),
  createModel<BankModule<46>, BankWidget<46>>("Curio-structure-2"),
  createModel<BankModule<47>, BankWidget<47>>("Curio-structure-3"),
  createModel<BankModule<48>, BankWidget<48>>("Curio-page-1"),
  createModel<BankModule<49>, BankWidget<49>>("Curio-page-2"),
};

// ---------- Focus: one item's sliders, chosen in the app ----------
static const CurioBank FOCUS_BANK = {
  "Curio-Focus", "Focus", CURIO_FOCUS_CHANNEL, 16, {
    { 1, 0, "The item itself", "" }, { 2, 0, "Slider 2", "" }, { 3, 0, "Slider 3", "" }, { 4, 0, "Slider 4", "" },
    { 5, 0, "Slider 5", "" }, { 6, 0, "Slider 6", "" }, { 7, 0, "Slider 7", "" }, { 8, 0, "Slider 8", "" },
    { 9, 0, "Slider 9", "" }, { 10, 0, "Slider 10", "" }, { 11, 0, "Slider 11", "" }, { 12, 0, "Slider 12", "" },
    { 13, 0, "Slider 13", "" }, { 14, 0, "Slider 14", "" }, { 15, 0, "Slider 15", "" }, { 16, 0, "Slider 16", "" },
  }
};
struct FocusModule : CurioModule {
  FocusModule() : CurioModule(&FOCUS_BANK) {}
};
struct FocusWidget : CurioWidget {
  FocusWidget(FocusModule* module) : CurioWidget(module, &FOCUS_BANK) {
    addChild(makeLabel(mm2px(Vec(4.f, 122.f)), mm2px(Vec(73.28f, 6.f)), "Pick the item in the app's VCV badge.", nvgRGB(0x6d, 0x65, 0x5d), 8.f));
  }
};
Model* modelCurioFocus = createModel<FocusModule, FocusWidget>("Curio-Focus");
