// Generated by vcv/tools/make-plugin.js. One generic module; each bank in bank.hpp is its own model.
#include "plugin.hpp"
#include "bank.hpp"

// 0 V is the item's From setting in the app, 10 V its To. Values go out as MIDI CC when they change.
// Every module remembers the MIDI device last chosen on any Curiosities module, so a new one is ready to go.
static json_t* lastMidiJ = NULL;

static const NVGcolor LEVEL_COLORS[4] = {
  nvgRGB(0xc4, 0x47, 0x2f), // curiosity
  nvgRGB(0xc9, 0x8a, 0x14), // suite
  nvgRGB(0x2f, 0x7f, 0x78), // proximity
  nvgRGB(0x5d, 0x4f, 0xa8), // proximity suite
};

// ---------- OSC over UDP to the desktop app's bridge (127.0.0.1:7000), the second way out besides MIDI ----------
// Address /curio/set/<level>/<id> with one float 0..1, as in the desktop bridge (apps/curiosities/desktop/README.md).
#if defined(ARCH_WIN)
  #include <winsock2.h>
  #include <ws2tcpip.h>
  typedef SOCKET curio_socket;
  #define CURIO_BAD_SOCKET INVALID_SOCKET
#else
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <arpa/inet.h>
  #include <unistd.h>
  typedef int curio_socket;
  #define CURIO_BAD_SOCKET (-1)
#endif
#include <cstring>

struct CurioOsc {
  curio_socket sock = CURIO_BAD_SOCKET;
  sockaddr_in addr;

  bool open() {
    if (sock != CURIO_BAD_SOCKET)
      return true;
#if defined(ARCH_WIN)
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif
    sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock == CURIO_BAD_SOCKET)
      return false;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(7000);
    addr.sin_addr.s_addr = htonl(0x7f000001); // 127.0.0.1
    return true;
  }

  static void pad(std::string& b) {
    do b.push_back('\0'); while (b.size() % 4);
  }

  // One OSC message with one big-endian int32 (",i").
  void sendInt(const std::string& address, int32_t v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",i";
    pad(b);
    uint32_t u = htonl((uint32_t) v);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }

  // One OSC message: the address, the type tag ",f", one big-endian float.
  void sendFloat(const std::string& address, float v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",f";
    pad(b);
    uint32_t u;
    std::memcpy(&u, &v, 4);
    u = htonl(u);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }
};
static CurioOsc curioOsc;

// "c:music" -> "/curio/set/c/music" (or "/curio/trigger/c/music")
static std::string oscAddress(const char* key, const char* verb = "set") {
  std::string k = key;
  size_t colon = k.find(':');
  if (colon == std::string::npos)
    return "";
  return std::string("/curio/") + verb + "/" + k.substr(0, colon) + "/" + k.substr(colon + 1);
}

struct CurioModule : Module {
  const CurioBank* bank;
  midi::Output midiOutput;
  int lastValues[16];
  float lastOsc[16];
  bool useOsc = false; // send OSC to the desktop app instead of MIDI
  bool gateOn[16] = {};
  dsp::ClockDivider sendDivider;
  dsp::ClockDivider rememberDivider;

  CurioModule(const CurioBank* b) : bank(b) {
    config(0, 32, 0, 0);
    for (int i = 0; i < 16; i++) {
      if (i < bank->count) {
        configInput(i, bank->jacks[i].label);
        configInput(16 + i, std::string(bank->jacks[i].label) + ": on/off gate (OSC)");
      }
      else {
        configInput(i, "Unused");
        configInput(16 + i, "Unused");
      }
    }
    sendDivider.setDivision(64);
    rememberDivider.setDivision(48000);
    onReset();
  }

  void onReset() override {
    for (int i = 0; i < 16; i++) {
      lastValues[i] = -1;
      lastOsc[i] = -1.f;
    }
    midiOutput.reset();
    if (lastMidiJ)
      midiOutput.fromJson(lastMidiJ);
    midiOutput.setChannel(bank->channel - 1);
  }

  void process(const ProcessArgs& args) override {
    if (rememberDivider.process()) {
      // Remember this module's device for the next one added.
      if (midiOutput.getDeviceId() >= 0) {
        if (lastMidiJ)
          json_decref(lastMidiJ);
        lastMidiJ = midiOutput.toJson();
      }
    }
    if (!sendDivider.process())
      return;
    if (useOsc && bank->jacks[0].key[0]) {
      // Gates switch the item on and off: /curio/trigger/<level>/<id> 1 on the rise, 0 on the fall.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[16 + i].isConnected())
          continue;
        bool high = inputs[16 + i].getVoltage() >= 1.f;
        if (high == gateOn[i])
          continue;
        gateOn[i] = high;
        curioOsc.sendInt(oscAddress(bank->jacks[i].key, "trigger"), high ? 1 : 0);
      }
      // OSC keeps fine steps: anything that moved by more than about 0.1% goes out.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[i].isConnected())
          continue;
        float m = clamp(inputs[i].getVoltage() / 10.f, 0.f, 1.f);
        if (std::fabs(m - lastOsc[i]) < 0.001f)
          continue;
        lastOsc[i] = m;
        curioOsc.sendFloat(oscAddress(bank->jacks[i].key), m);
      }
      return;
    }
    for (int i = 0; i < bank->count; i++) {
      if (!inputs[i].isConnected())
        continue;
      int v = (int) clamp(std::round(inputs[i].getVoltage() / 10.f * 127.f), 0.f, 127.f);
      if (v == lastValues[i])
        continue;
      lastValues[i] = v;
      midi::Message m;
      m.setStatus(0xb);
      m.setNote(bank->jacks[i].cc);
      m.setValue(v);
      midiOutput.sendMessage(m);
    }
  }

  json_t* dataToJson() override {
    json_t* rootJ = json_object();
    json_object_set_new(rootJ, "midi", midiOutput.toJson());
    json_object_set_new(rootJ, "osc", json_boolean(useOsc));
    return rootJ;
  }

  void dataFromJson(json_t* rootJ) override {
    json_t* midiJ = json_object_get(rootJ, "midi");
    if (midiJ)
      midiOutput.fromJson(midiJ);
    json_t* oscJ = json_object_get(rootJ, "osc");
    if (oscJ)
      useOsc = json_boolean_value(oscJ);
    // The channel belongs to the bank, whatever a saved patch says.
    midiOutput.setChannel(bank->channel - 1);
  }
};

// A name printed beside a jack, colored by level. SVG text does not render in Rack, so labels are drawn here.
struct CurioLabel : Widget {
  std::string text;
  NVGcolor color = nvgRGB(0x21, 0x1d, 0x1a);
  float fontSize = 9.f;

  void draw(const DrawArgs& args) override {
    std::shared_ptr<window::Font> font = APP->window->loadFont(asset::system("res/fonts/DejaVuSans.ttf"));
    if (!font || font->handle < 0)
      return;
    nvgFontFaceId(args.vg, font->handle);
    nvgFontSize(args.vg, fontSize);
    nvgFillColor(args.vg, color);
    nvgTextAlign(args.vg, NVG_ALIGN_LEFT | NVG_ALIGN_TOP);
    nvgTextLineHeight(args.vg, 1.05f);
    nvgTextBox(args.vg, 0, 0, box.size.x, text.c_str(), NULL);
  }
};

static CurioLabel* makeLabel(Vec pos, Vec size, std::string text, NVGcolor color, float fontSize) {
  CurioLabel* l = new CurioLabel;
  l->box.pos = pos;
  l->box.size = size;
  l->text = text;
  l->color = color;
  l->fontSize = fontSize;
  return l;
}

// Two columns of eight jacks, each with its name to the right.
static void addJacks(ModuleWidget* w, Module* module, const CurioBank* bank, int count, const char* const* names, const int* levels) {
  for (int i = 0; i < 16; i++) {
    int col = i / 8;
    int row = i % 8;
    float x = 6.f + col * 40.f;
    float y = 30.f + row * 12.f;
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, y)), module, i));
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x + 8.5f, y)), module, 16 + i));
    if (i < count)
      w->addChild(makeLabel(mm2px(Vec(x + 13.f, y - 4.2f)), mm2px(Vec(23.f, 9.f)), names[i], LEVEL_COLORS[levels[i]], 8.f));
  }
}

struct CurioWidget : ModuleWidget {
  const CurioBank* bank;

  CurioWidget(CurioModule* module, const CurioBank* b) : bank(b) {
    setModule(module);
    setPanel(createPanel(asset::plugin(pluginInstance, "res/Curio.svg")));
    addChild(makeLabel(mm2px(Vec(4.f, 6.f)), mm2px(Vec(73.28f, 8.f)), bank->title, nvgRGB(0x21, 0x1d, 0x1a), 14.f));
    addChild(makeLabel(mm2px(Vec(4.f, 14.f)), mm2px(Vec(73.28f, 8.f)),
      string::f("%sMIDI ch %d, CC %d-%d. Left jack: 0 V From, 10 V To. Right jack: on/off gate (OSC).", bank->port > 1 ? string::f("Port %d, ", bank->port).c_str() : "", bank->channel, bank->jacks[0].cc, bank->jacks[bank->count - 1].cc),
      nvgRGB(0x6d, 0x65, 0x5d), 8.f));
    const char* names[16];
    int levels[16];
    for (int i = 0; i < 16; i++) {
      names[i] = i < bank->count ? bank->jacks[i].label : "";
      levels[i] = i < bank->count ? bank->jacks[i].level : 0;
    }
    addJacks(this, module, bank, bank->count, names, levels);
  }

  void appendContextMenu(Menu* menu) override {
    CurioModule* module = dynamic_cast<CurioModule*>(this->module);
    if (!module)
      return;
    menu->addChild(new MenuSeparator);
    if (bank->jacks[0].key[0])
      menu->addChild(createBoolPtrMenuItem("Send by OSC to the desktop app (port 7000)", "", &module->useOsc));
    menu->addChild(createMenuLabel("MIDI output (to the Curiosities app in a browser)"));
    appendMidiMenu(menu, &module->midiOutput);
  }
};

// Each bank is its own model: a module and widget type fixed to one entry of CURIO_BANKS.
template <int N>
struct BankModule : CurioModule {
  BankModule() : CurioModule(&CURIO_BANKS[N]) {}
};
template <int N>
struct BankWidget : CurioWidget {
  BankWidget(BankModule<N>* module) : CurioWidget(module, &CURIO_BANKS[N]) {}
};

Model* curioModels[] = {
  createModel<BankModule<0>, BankWidget<0>>("Curio-camera-angle-1"),
  createModel<BankModule<1>, BankWidget<1>>("Curio-camera-angle-2"),
  createModel<BankModule<2>, BankWidget<2>>("Curio-camera-angle-3"),
  createModel<BankModule<3>, BankWidget<3>>("Curio-camera-motion-1"),
  createModel<BankModule<4>, BankWidget<4>>("Curio-camera-motion-2"),
  createModel<BankModule<5>, BankWidget<5>>("Curio-camera-motion-3"),
  createModel<BankModule<6>, BankWidget<6>>("Curio-character-motion-1"),
  createModel<BankModule<7>, BankWidget<7>>("Curio-character-motion-2"),
  createModel<BankModule<8>, BankWidget<8>>("Curio-character-motion-3"),
  createModel<BankModule<9>, BankWidget<9>>("Curio-character-motion-4"),
  createModel<BankModule<10>, BankWidget<10>>("Curio-placement-1"),
  createModel<BankModule<11>, BankWidget<11>>("Curio-placement-2"),
  createModel<BankModule<12>, BankWidget<12>>("Curio-placement-3"),
  createModel<BankModule<13>, BankWidget<13>>("Curio-placement-4"),
  createModel<BankModule<14>, BankWidget<14>>("Curio-lines-1"),
  createModel<BankModule<15>, BankWidget<15>>("Curio-lines-2"),
  createModel<BankModule<16>, BankWidget<16>>("Curio-lines-3"),
  createModel<BankModule<17>, BankWidget<17>>("Curio-lines-4"),
  createModel<BankModule<18>, BankWidget<18>>("Curio-movement-lines-1"),
  createModel<BankModule<19>, BankWidget<19>>("Curio-movement-lines-2"),
  createModel<BankModule<20>, BankWidget<20>>("Curio-movement-lines-3"),
  createModel<BankModule<21>, BankWidget<21>>("Curio-background-1"),
  createModel<BankModule<22>, BankWidget<22>>("Curio-background-2"),
  createModel<BankModule<23>, BankWidget<23>>("Curio-background-3"),
  createModel<BankModule<24>, BankWidget<24>>("Curio-light-1"),
  createModel<BankModule<25>, BankWidget<25>>("Curio-light-2"),
  createModel<BankModule<26>, BankWidget<26>>("Curio-light-3"),
  createModel<BankModule<27>, BankWidget<27>>("Curio-light-4"),
  createModel<BankModule<28>, BankWidget<28>>("Curio-light-5"),
  createModel<BankModule<29>, BankWidget<29>>("Curio-light-6"),
  createModel<BankModule<30>, BankWidget<30>>("Curio-effects-1"),
  createModel<BankModule<31>, BankWidget<31>>("Curio-effects-2"),
  createModel<BankModule<32>, BankWidget<32>>("Curio-effects-3"),
  createModel<BankModule<33>, BankWidget<33>>("Curio-effects-4"),
  createModel<BankModule<34>, BankWidget<34>>("Curio-effects-5"),
  createModel<BankModule<35>, BankWidget<35>>("Curio-arc-1"),
  createModel<BankModule<36>, BankWidget<36>>("Curio-arc-2"),
  createModel<BankModule<37>, BankWidget<37>>("Curio-arc-3"),
  createModel<BankModule<38>, BankWidget<38>>("Curio-plot-1"),
  createModel<BankModule<39>, BankWidget<39>>("Curio-plot-2"),
  createModel<BankModule<40>, BankWidget<40>>("Curio-plot-3"),
  createModel<BankModule<41>, BankWidget<41>>("Curio-plot-4"),
  createModel<BankModule<42>, BankWidget<42>>("Curio-mindset-1"),
  createModel<BankModule<43>, BankWidget<43>>("Curio-mindset-2"),
  createModel<BankModule<44>, BankWidget<44>>("Curio-focus-1"),
  createModel<BankModule<45>, BankWidget<45>>("Curio-focus-2"),
  createModel<BankModule<46>, BankWidget<46>>("Curio-archetype-1"),
  createModel<BankModule<47>, BankWidget<47>>("Curio-archetype-2"),
  createModel<BankModule<48>, BankWidget<48>>("Curio-archetype-3"),
  createModel<BankModule<49>, BankWidget<49>>("Curio-archetype-4"),
  createModel<BankModule<50>, BankWidget<50>>("Curio-herd-1"),
  createModel<BankModule<51>, BankWidget<51>>("Curio-herd-2"),
  createModel<BankModule<52>, BankWidget<52>>("Curio-wardrobe-1"),
  createModel<BankModule<53>, BankWidget<53>>("Curio-wardrobe-2"),
  createModel<BankModule<54>, BankWidget<54>>("Curio-wardrobe-3"),
  createModel<BankModule<55>, BankWidget<55>>("Curio-color-1"),
  createModel<BankModule<56>, BankWidget<56>>("Curio-color-2"),
  createModel<BankModule<57>, BankWidget<57>>("Curio-color-3"),
  createModel<BankModule<58>, BankWidget<58>>("Curio-set-1"),
  createModel<BankModule<59>, BankWidget<59>>("Curio-set-2"),
  createModel<BankModule<60>, BankWidget<60>>("Curio-set-3"),
  createModel<BankModule<61>, BankWidget<61>>("Curio-set-4"),
  createModel<BankModule<62>, BankWidget<62>>("Curio-set-5"),
  createModel<BankModule<63>, BankWidget<63>>("Curio-emotion-1"),
  createModel<BankModule<64>, BankWidget<64>>("Curio-emotion-2"),
  createModel<BankModule<65>, BankWidget<65>>("Curio-emotion-3"),
  createModel<BankModule<66>, BankWidget<66>>("Curio-emotion-4"),
  createModel<BankModule<67>, BankWidget<67>>("Curio-emotion-5"),
  createModel<BankModule<68>, BankWidget<68>>("Curio-emotion-6"),
  createModel<BankModule<69>, BankWidget<69>>("Curio-emotion-7"),
  createModel<BankModule<70>, BankWidget<70>>("Curio-emotion-8"),
  createModel<BankModule<71>, BankWidget<71>>("Curio-emotion-9"),
  createModel<BankModule<72>, BankWidget<72>>("Curio-emo-road-1"),
  createModel<BankModule<73>, BankWidget<73>>("Curio-emo-road-2"),
  createModel<BankModule<74>, BankWidget<74>>("Curio-emo-road-3"),
  createModel<BankModule<75>, BankWidget<75>>("Curio-emo-road-4"),
  createModel<BankModule<76>, BankWidget<76>>("Curio-emo-road-5"),
  createModel<BankModule<77>, BankWidget<77>>("Curio-emo-road-6"),
  createModel<BankModule<78>, BankWidget<78>>("Curio-comedy-1"),
  createModel<BankModule<79>, BankWidget<79>>("Curio-comedy-2"),
  createModel<BankModule<80>, BankWidget<80>>("Curio-comedy-3"),
  createModel<BankModule<81>, BankWidget<81>>("Curio-comedy-4"),
  createModel<BankModule<82>, BankWidget<82>>("Curio-comedy-5"),
  createModel<BankModule<83>, BankWidget<83>>("Curio-comedy-6"),
  createModel<BankModule<84>, BankWidget<84>>("Curio-comedy-7"),
  createModel<BankModule<85>, BankWidget<85>>("Curio-comedy-8"),
  createModel<BankModule<86>, BankWidget<86>>("Curio-comedy-9"),
  createModel<BankModule<87>, BankWidget<87>>("Curio-comedy-10"),
  createModel<BankModule<88>, BankWidget<88>>("Curio-comedy-11"),
  createModel<BankModule<89>, BankWidget<89>>("Curio-comedy-mix-1"),
  createModel<BankModule<90>, BankWidget<90>>("Curio-comedy-mix-2"),
  createModel<BankModule<91>, BankWidget<91>>("Curio-comedy-mix-3"),
  createModel<BankModule<92>, BankWidget<92>>("Curio-comedy-mix-4"),
  createModel<BankModule<93>, BankWidget<93>>("Curio-comedy-mix-5"),
  createModel<BankModule<94>, BankWidget<94>>("Curio-music-1"),
  createModel<BankModule<95>, BankWidget<95>>("Curio-music-2"),
  createModel<BankModule<96>, BankWidget<96>>("Curio-music-3"),
  createModel<BankModule<97>, BankWidget<97>>("Curio-music-4"),
  createModel<BankModule<98>, BankWidget<98>>("Curio-music-5"),
  createModel<BankModule<99>, BankWidget<99>>("Curio-music-6"),
  createModel<BankModule<100>, BankWidget<100>>("Curio-structure-1"),
  createModel<BankModule<101>, BankWidget<101>>("Curio-structure-2"),
  createModel<BankModule<102>, BankWidget<102>>("Curio-structure-3"),
  createModel<BankModule<103>, BankWidget<103>>("Curio-structure-4"),
  createModel<BankModule<104>, BankWidget<104>>("Curio-structure-5"),
  createModel<BankModule<105>, BankWidget<105>>("Curio-structure-6"),
  createModel<BankModule<106>, BankWidget<106>>("Curio-page-1"),
  createModel<BankModule<107>, BankWidget<107>>("Curio-page-2"),
  createModel<BankModule<108>, BankWidget<108>>("Curio-page-3"),
  createModel<BankModule<109>, BankWidget<109>>("Curio-transitions-1"),
  createModel<BankModule<110>, BankWidget<110>>("Curio-transitions-2"),
  createModel<BankModule<111>, BankWidget<111>>("Curio-transitions-3"),
  createModel<BankModule<112>, BankWidget<112>>("Curio-grade-1"),
  createModel<BankModule<113>, BankWidget<113>>("Curio-grade-2"),
  createModel<BankModule<114>, BankWidget<114>>("Curio-titles-1"),
  createModel<BankModule<115>, BankWidget<115>>("Curio-titles-2"),
  createModel<BankModule<116>, BankWidget<116>>("Curio-speed-1"),
  createModel<BankModule<117>, BankWidget<117>>("Curio-speed-2"),
  createModel<BankModule<118>, BankWidget<118>>("Curio-speed-3"),
  createModel<BankModule<119>, BankWidget<119>>("Curio-audio-mix-1"),
  createModel<BankModule<120>, BankWidget<120>>("Curio-audio-mix-2"),
  createModel<BankModule<121>, BankWidget<121>>("Curio-audio-mix-3"),
  createModel<BankModule<122>, BankWidget<122>>("Curio-layers-1"),
  createModel<BankModule<123>, BankWidget<123>>("Curio-layers-2"),
  createModel<BankModule<124>, BankWidget<124>>("Curio-layers-3"),
  createModel<BankModule<125>, BankWidget<125>>("Curio-layers-4"),
  createModel<BankModule<126>, BankWidget<126>>("Curio-canvas-1"),
  createModel<BankModule<127>, BankWidget<127>>("Curio-canvas-2"),
};

// ---------- Focus: one item's sliders, chosen in the app ----------
static const CurioBank FOCUS_BANK = {
  "Curio-Focus", "Focus", 1, CURIO_FOCUS_CHANNEL, 16, {
    { 1, 0, "The item itself", "" }, { 2, 0, "Slider 2", "" }, { 3, 0, "Slider 3", "" }, { 4, 0, "Slider 4", "" },
    { 5, 0, "Slider 5", "" }, { 6, 0, "Slider 6", "" }, { 7, 0, "Slider 7", "" }, { 8, 0, "Slider 8", "" },
    { 9, 0, "Slider 9", "" }, { 10, 0, "Slider 10", "" }, { 11, 0, "Slider 11", "" }, { 12, 0, "Slider 12", "" },
    { 13, 0, "Slider 13", "" }, { 14, 0, "Slider 14", "" }, { 15, 0, "Slider 15", "" }, { 16, 0, "Slider 16", "" },
  }
};
struct FocusModule : CurioModule {
  FocusModule() : CurioModule(&FOCUS_BANK) {}
};
struct FocusWidget : CurioWidget {
  FocusWidget(FocusModule* module) : CurioWidget(module, &FOCUS_BANK) {
    addChild(makeLabel(mm2px(Vec(4.f, 122.f)), mm2px(Vec(73.28f, 6.f)), "Pick the item in the app's VCV badge.", nvgRGB(0x6d, 0x65, 0x5d), 8.f));
  }
};
Model* modelCurioFocus = createModel<FocusModule, FocusWidget>("Curio-Focus");

// ---------- Return: values coming back from the desktop app ----------
// The desktop bridge sends /curio/value/<level>/<id> f (0..1) on UDP 7001 about 30 times a second. One socket is
// shared by every Return module; whichever module gets the lock first reads what has arrived.
#include <map>
#include <mutex>
#if !defined(ARCH_WIN)
  #include <fcntl.h>
#endif

struct CurioReceiver {
  std::mutex lock;
  curio_socket sock = CURIO_BAD_SOCKET;
  bool failed = false;
  std::map<std::string, float> values; // "c:music" -> 0..1

  bool open() {
    if (sock != CURIO_BAD_SOCKET)
      return true;
    if (failed)
      return false;
#if defined(ARCH_WIN)
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif
    sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock == CURIO_BAD_SOCKET) {
      failed = true;
      return false;
    }
    int yes = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char*) &yes, sizeof(yes));
#if defined(ARCH_WIN)
    u_long nb = 1;
    ioctlsocket(sock, FIONBIO, &nb);
#else
    fcntl(sock, F_SETFL, fcntl(sock, F_GETFL, 0) | O_NONBLOCK);
#endif
    sockaddr_in a;
    std::memset(&a, 0, sizeof(a));
    a.sin_family = AF_INET;
    a.sin_port = htons(7001);
    a.sin_addr.s_addr = htonl(0x7f000001);
    if (bind(sock, (const sockaddr*) &a, sizeof(a)) != 0) {
      failed = true;
      return false;
    }
    return true;
  }

  static size_t padded(size_t n) {
    return (n + 4) & ~((size_t) 3);
  }

  // One OSC message or bundle element. Only /curio/value/<level>/<id> with a float is kept.
  void parse(const char* d, size_t n) {
    if (n >= 16 && std::memcmp(d, "#bundle", 8) == 0) {
      size_t i = 16;
      while (i + 4 <= n) {
        uint32_t len;
        std::memcpy(&len, d + i, 4);
        len = ntohl(len);
        i += 4;
        if (i + len > n)
          break;
        parse(d + i, len);
        i += len;
      }
      return;
    }
    size_t alen = strnlen(d, n);
    if (alen == n)
      return;
    std::string address(d, alen);
    size_t t = padded(alen);
    if (t + 2 > n || d[t] != ',' || d[t + 1] != 'f')
      return;
    size_t v = t + padded(strnlen(d + t, n - t));
    if (v + 4 > n)
      return;
    const std::string prefix = "/curio/value/";
    if (address.compare(0, prefix.size(), prefix) != 0)
      return;
    std::string rest = address.substr(prefix.size());
    size_t slash = rest.find('/');
    if (slash == std::string::npos)
      return;
    uint32_t u;
    std::memcpy(&u, d + v, 4);
    u = ntohl(u);
    float f;
    std::memcpy(&f, &u, 4);
    values[rest.substr(0, slash) + ":" + rest.substr(slash + 1)] = f;
  }

  void poll() {
    if (!open())
      return;
    char buf[2048];
    for (int k = 0; k < 256; k++) {
      int got = (int) recvfrom(sock, buf, sizeof(buf), 0, NULL, NULL);
      if (got <= 0)
        break;
      parse(buf, (size_t) got);
    }
  }
};
static CurioReceiver curioReceiver;

struct ReturnModule : Module {
  const CurioBank* bank = NULL; // the bank of the module on the left, if it is a Curiosities module
  dsp::ClockDivider divider;
  float out[16] = {};

  ReturnModule() {
    config(0, 0, 16, 0);
    for (int i = 0; i < 16; i++)
      configOutput(i, string::f("Value back from the app %d", i + 1));
    divider.setDivision(256);
  }

  void process(const ProcessArgs& args) override {
    if (divider.process()) {
      CurioModule* left = dynamic_cast<CurioModule*>(leftExpander.module);
      bank = (left && left->bank->jacks[0].key[0]) ? left->bank : NULL;
      if (bank && curioReceiver.lock.try_lock()) {
        curioReceiver.poll();
        for (int i = 0; i < 16; i++) {
          auto it = i < bank->count ? curioReceiver.values.find(bank->jacks[i].key) : curioReceiver.values.end();
          out[i] = it != curioReceiver.values.end() ? clamp(it->second, 0.f, 1.f) * 10.f : 0.f;
        }
        curioReceiver.lock.unlock();
      }
    }
    for (int i = 0; i < 16; i++)
      outputs[i].setVoltage(bank ? out[i] : 0.f);
  }
};

// A label that names the item of the module on the left, so the same Return module works beside any bank.
struct ReturnLabel : CurioLabel {
  ReturnModule* module = NULL;
  int index = 0;
  void draw(const DrawArgs& args) override {
    text = (module && module->bank && index < module->bank->count) ? module->bank->jacks[index].label : "";
    if (index == 0 && !(module && module->bank))
      text = "Place me right of a Curiosities module";
    CurioLabel::draw(args);
  }
};

struct ReturnWidget : ModuleWidget {
  ReturnWidget(ReturnModule* module) {
    setModule(module);
    setPanel(createPanel(asset::plugin(pluginInstance, "res/Curio.svg")));
    addChild(makeLabel(mm2px(Vec(4.f, 6.f)), mm2px(Vec(73.f, 8.f)), "Return", nvgRGB(0x21, 0x1d, 0x1a), 14.f));
    addChild(makeLabel(mm2px(Vec(4.f, 14.f)), mm2px(Vec(73.f, 8.f)), "Values back from the desktop app, 0 to 10 V (OSC on port 7001).", nvgRGB(0x6d, 0x65, 0x5d), 8.f));
    for (int i = 0; i < 16; i++) {
      int col = i / 8;
      int row = i % 8;
      float x = 6.f + col * 40.f;
      float y = 30.f + row * 12.f;
      addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(x, y)), module, i));
      ReturnLabel* l = new ReturnLabel;
      l->box.pos = mm2px(Vec(x + 5.f, y - 4.2f));
      l->box.size = mm2px(Vec(30.f, 9.f));
      l->module = module;
      l->index = i;
      l->fontSize = 8.f;
      addChild(l);
    }
  }
};
Model* modelCurioReturn = createModel<ReturnModule, ReturnWidget>("Curio-Return");
