// Generated by vcv/tools/make-plugin.js.
#include "plugin.hpp"
#include "bank.hpp"

Plugin* pluginInstance;

void init(Plugin* p) {
  pluginInstance = p;
  for (int i = 0; i < CURIO_BANK_COUNT; i++)
    p->addModel(curioModels[i]);
  p->addModel(modelCurioFocus);
}
