/* The filmmaking curiosities catalog (apps/curiosities/docs/filmmaking-curiosities-catalog.md),
   as data. 157 curiosities, 10 development moves, 24 suites, 22 proximities.
   Regenerate from the doc if it changes; ids match catalog.js where a row already exists.
   The Edit group's "density" is visualDensity here, since Dynamics already uses density. */

const LIBRARY = {
  curiosities: [
    {"id": "shotSize", "group": "Camera", "label": "Shot size", "view": "A strip of frame sizes, one per beat", "values": "wide, medium, close, insert", "source": "board"},
    {"id": "angleHeight", "group": "Camera", "label": "Angle height", "view": "A line that rises and falls with the lens height", "values": "eye, low, high, overhead, floor", "source": "board"},
    {"id": "lensLength", "group": "Camera", "label": "Lens length", "view": "Focal length per shot", "values": "14 to 200 mm", "source": "board, Maya"},
    {"id": "dutch", "group": "Camera", "label": "Dutch / level", "view": "Horizon tilt per shot", "values": "0 to 45 degrees", "source": "board"},
    {"id": "pov", "group": "Camera", "label": "Point of view", "view": "Whose eyes, colored by person", "values": "a person, or nobody", "source": "board"},
    {"id": "angleCount", "group": "Camera", "label": "Angles per scene", "view": "Count of distinct setups", "values": "1 to 8", "source": "board"},
    {"id": "angleFamily", "group": "Camera", "label": "Angles grouped", "view": "A band naming the cutting pattern", "values": "coverage, oner, montage, handheld", "source": "board"},
    {"id": "angleChange", "group": "Camera", "label": "When the angle changes", "view": "Cut ticks set against lines and actions", "values": "on the line, on the action, both, locked", "source": "board, chat"},
    {"id": "angleToLine", "group": "Camera", "label": "Angle matched to the line", "view": "Shot size beside each kind of line", "values": "pairs", "source": "board"},
    {"id": "angleToAction", "group": "Camera", "label": "Angle matched to the action", "view": "Shot size beside each kind of action", "values": "pairs", "source": "board"},
    {"id": "cutRate", "group": "Camera", "label": "Frequency of angle changes", "view": "Cuts per minute as a curve", "values": "cuts per minute", "source": "board, chat"},
    {"id": "shotDuration", "group": "Camera", "label": "Hold", "view": "Bar length per shot", "values": "seconds", "source": "board"},
    {"id": "depthOfField", "group": "Camera", "label": "Depth of field", "view": "How deep the sharp zone is", "values": "f-stop 1.4 to 22", "source": "Maya"},
    {"id": "rackFocus", "group": "Camera", "label": "Focus pull", "view": "When focus moves from one subject to another", "values": "none, on the line, on the action", "source": "Maya"},
    {"id": "motionBlur", "group": "Camera", "label": "Motion blur", "view": "Blur amount per shot", "values": "shutter 45 to 360 degrees", "source": "Maya"},
    {"id": "aspect", "group": "Camera", "label": "Frame shape", "view": "Aspect ratio per shot or panel", "values": "1.33, 1.85, 2.39, custom", "source": "new"},
    {"id": "composition", "group": "Camera", "label": "Where the subject sits", "view": "A dot for the subject's place in frame", "values": "left third, center, right third", "source": "new"},
    {"id": "emptySpace", "group": "Camera", "label": "Empty frame", "view": "Share of frame with nothing in it", "values": "0 to 100 percent", "source": "new"},
    {"id": "cameraCarry", "group": "Camera move", "label": "Camera carry", "view": "Still frame, smooth line or wobble", "values": "locked, smooth, handheld", "source": "board"},
    {"id": "cameraMove", "group": "Camera move", "label": "Camera move", "view": "The move named per shot", "values": "none, pan, tilt, push in, pull out, track, crane, zoom, orbit", "source": "board"},
    {"id": "moveSpeed", "group": "Camera move", "label": "Move speed", "view": "Speed curve of the camera", "values": "1 to 5", "source": "board"},
    {"id": "moveFollows", "group": "Camera move", "label": "Move follows", "view": "What the move is tied to", "values": "character, object, neither", "source": "board, chat"},
    {"id": "moveOn", "group": "Camera move", "label": "Move starts on", "view": "The cue that starts each move", "values": "line, action, breath, none", "source": "board"},
    {"id": "cameraOwner", "group": "Camera move", "label": "Camera owner", "view": "Authored or player camera", "values": "authored, player", "source": "board"},
    {"id": "moveToVolume", "group": "Camera move", "label": "Move against loudness", "view": "Camera speed laid over dialogue loudness", "values": "moves on loud, moves on soft, ignores", "source": "chat"},
    {"id": "moveTemper", "group": "Camera move", "label": "Move temper", "view": "The camera's attitude to the action", "values": "1 loving to 5 aggressive", "source": "chat"},
    {"id": "cameraShake", "group": "Camera move", "label": "Shake", "view": "Shake amplitude per beat", "values": "0 to 5", "source": "new"},
    {"id": "speedRamp", "group": "Camera move", "label": "Time speed", "view": "Playback speed of the shot", "values": "0.25x to 4x, ramps", "source": "Maya"},
    {"id": "characterPath", "group": "Motion", "label": "Character path", "view": "Each person's path drawn on a floor plan", "values": "still, cross, approach, retreat, circle", "source": "board"},
    {"id": "characterSpeed", "group": "Motion", "label": "Character speed", "view": "Speed curve per person", "values": "1 to 5", "source": "board"},
    {"id": "characterToLens", "group": "Motion", "label": "Toward the lens", "view": "Direction against the camera", "values": "toward, away, across", "source": "board"},
    {"id": "whoMoves", "group": "Motion", "label": "Who moves", "view": "Who travels during each line", "values": "speaker, listener, both, neither", "source": "board"},
    {"id": "bodyEnter", "group": "Motion", "label": "Body in frame", "view": "Entrances and exits", "values": "already, enters, leaves", "source": "board"},
    {"id": "objectKind", "group": "Motion", "label": "Object", "view": "What the moving thing is", "values": "prop, door, screen, vehicle, food", "source": "board"},
    {"id": "objectPath", "group": "Motion", "label": "Object path", "view": "The object's path", "values": "still, lift, drop, slide, open, pass", "source": "board"},
    {"id": "objectSpeed", "group": "Motion", "label": "Object speed", "view": "Speed curve of the object", "values": "1 to 5", "source": "board"},
    {"id": "objectEnter", "group": "Motion", "label": "Object in frame", "view": "Object entrances and exits", "values": "stays, enters, leaves", "source": "board"},
    {"id": "spacing", "group": "Animation", "label": "Spacing", "view": "The shape of each move's curve", "values": "even, ease in, ease out, ease both, snap", "source": "Maya"},
    {"id": "stepping", "group": "Animation", "label": "Drawn on", "view": "Frames each pose holds", "values": "ones, twos, threes", "source": "Maya"},
    {"id": "anticipation", "group": "Animation", "label": "Anticipation", "view": "Wind-up before each move", "values": "none, small, big", "source": "Maya"},
    {"id": "overshoot", "group": "Animation", "label": "Overshoot", "view": "What happens after each stop", "values": "none, settle, bounce", "source": "Maya"},
    {"id": "overlap", "group": "Animation", "label": "Overlap", "view": "Parts still moving after the body stops", "values": "none, hair, cloth, hands, all", "source": "Maya"},
    {"id": "arcs", "group": "Animation", "label": "Path shape", "view": "Motion trails of head and hands", "values": "straight, arc, figure eight", "source": "Maya"},
    {"id": "leadPart", "group": "Animation", "label": "Leads the move", "view": "Which part starts first", "values": "eyes, head, hips, hands", "source": "Maya"},
    {"id": "squash", "group": "Animation", "label": "Squash and stretch", "view": "Deformation amount", "values": "0 to 5", "source": "Maya"},
    {"id": "poseRate", "group": "Animation", "label": "Key poses per line", "view": "Held poses per line of dialogue", "values": "1 to 8", "source": "Maya"},
    {"id": "faceIntensity", "group": "Animation", "label": "Facial expression", "view": "Expression and its strength per beat", "values": "expression name, 0 to 5", "source": "Maya"},
    {"id": "lipSync", "group": "Animation", "label": "Mouth shapes", "view": "Mouth shapes per second of speech", "values": "0 to 12", "source": "Maya"},
    {"id": "gesture", "group": "Body", "label": "Size of gesture", "view": "Gesture size per beat", "values": "none, hand, arm, whole body", "source": "board"},
    {"id": "stillness", "group": "Body", "label": "Stillness", "view": "How much of the person moves", "values": "0 to 5", "source": "board"},
    {"id": "blink", "group": "Body", "label": "Blink", "view": "Blinks marked as beats", "values": "yes, no", "source": "board"},
    {"id": "gazeShift", "group": "Body", "label": "Eye darts", "view": "Eye movements per beat", "values": "0 to 8", "source": "new"},
    {"id": "posture", "group": "Body", "label": "Posture", "view": "Open or closed body", "values": "open, neutral, closed", "source": "new"},
    {"id": "touch", "group": "Body", "label": "Touch", "view": "Who touches whom, and when", "values": "pairs", "source": "new"},
    {"id": "key", "group": "Light", "label": "Key direction", "view": "Where the main light comes from", "values": "side, front, back, under, none", "source": "board, chat"},
    {"id": "contrast", "group": "Light", "label": "Contrast", "view": "Stops between key and fill", "values": "0 to 6 stops", "source": "board, Maya"},
    {"id": "colorTemp", "group": "Light", "label": "Color of the light", "view": "Light color per shot", "values": "2700 to 7500 K", "source": "board, Maya"},
    {"id": "lighting", "group": "Light", "label": "Lighting", "view": "One look per panel", "values": "dusk, flat, practical, hard, moon", "source": "board"},
    {"id": "timeOfDay", "group": "Light", "label": "Time of day", "view": "The sun's job", "values": "dawn, day, dusk, night", "source": "board"},
    {"id": "softness", "group": "Light", "label": "Softness", "view": "Hard or soft shadows", "values": "hard, soft", "source": "Maya"},
    {"id": "rim", "group": "Light", "label": "Rim light", "view": "Edge light on figures", "values": "off, thin, strong", "source": "Maya"},
    {"id": "lightCount", "group": "Light", "label": "Sources", "view": "Lights doing work in the shot", "values": "1 to 8", "source": "Maya"},
    {"id": "practicalInFrame", "group": "Light", "label": "Source in frame", "view": "Visible lamps, screens, fires", "values": "yes, no", "source": "Maya"},
    {"id": "lightShape", "group": "Light", "label": "Shaped light", "view": "Patterns cast by gobo, blocker, barndoor", "values": "open, blinds, leaves, barndoor", "source": "Maya"},
    {"id": "atmosphere", "group": "Light", "label": "Air", "view": "Haze in the light", "values": "clear, haze, beams", "source": "Maya"},
    {"id": "lightChange", "group": "Light", "label": "When the light changes", "view": "Light-change ticks against cuts and actions", "values": "never, on the cut, on the action, during the hold", "source": "Maya"},
    {"id": "valueKey", "group": "Light", "label": "Brightness key", "view": "Overall brightness by section", "values": "low key, mid, high key", "source": "music"},
    {"id": "renderStyle", "group": "Shading and color", "label": "Render style", "view": "The look of the frame", "values": "photoreal, painterly, toon, flat", "source": "Maya"},
    {"id": "lineWeight", "group": "Shading and color", "label": "Ink line", "view": "Outline thickness", "values": "none, thin, heavy", "source": "Maya"},
    {"id": "gloss", "group": "Shading and color", "label": "Gloss", "view": "Surface shine", "values": "matte, satin, mirror", "source": "Maya"},
    {"id": "wetness", "group": "Shading and color", "label": "Wetness", "view": "How wet surfaces read", "values": "dry, damp, soaked", "source": "Maya"},
    {"id": "skinLight", "group": "Shading and color", "label": "Light in skin", "view": "Subsurface glow in skin", "values": "0 to 5", "source": "Maya"},
    {"id": "glow", "group": "Shading and color", "label": "Something glows", "view": "Emitting things in frame", "values": "none, object, person, room", "source": "Maya"},
    {"id": "wear", "group": "Shading and color", "label": "Wear", "view": "Damage and dirt over the scene", "values": "new, used, ruined", "source": "Maya"},
    {"id": "saturation", "group": "Shading and color", "label": "Color saturation", "view": "Saturation of the frame", "values": "0 to 5", "source": "Maya"},
    {"id": "palette", "group": "Shading and color", "label": "Dominant color", "view": "The main hue per shot as a color strip", "values": "hue", "source": "new"},
    {"id": "windForce", "group": "Dynamics, fur and Bifrost", "label": "Wind", "view": "Wind strength", "values": "0 to 5", "source": "Maya"},
    {"id": "turbulence", "group": "Dynamics, fur and Bifrost", "label": "Chaos", "view": "Calm drift against gusts", "values": "0 to 5", "source": "Maya"},
    {"id": "clothResponse", "group": "Dynamics, fur and Bifrost", "label": "Cloth reacts", "view": "How cloth moves", "values": "stiff, loose, flutter", "source": "Maya"},
    {"id": "impacts", "group": "Dynamics, fur and Bifrost", "label": "Impacts per beat", "view": "Collisions the audience notices", "values": "0 to 8", "source": "Maya"},
    {"id": "breakage", "group": "Dynamics, fur and Bifrost", "label": "Breaks", "view": "Objects that fail", "values": "holds, cracks, shatters", "source": "Maya"},
    {"id": "settleTime", "group": "Dynamics, fur and Bifrost", "label": "Settle time", "view": "Beats until things are still after a hit", "values": "beats", "source": "Maya"},
    {"id": "gravityFeel", "group": "Dynamics, fur and Bifrost", "label": "Weight", "view": "How heavy the world feels", "values": "floaty, real, heavy", "source": "Maya"},
    {"id": "furLength", "group": "Dynamics, fur and Bifrost", "label": "Fur length", "view": "Hair or fur length", "values": "short, medium, long", "source": "Maya"},
    {"id": "clump", "group": "Dynamics, fur and Bifrost", "label": "Clumping", "view": "Fine or matted fur", "values": "fine, tufted, matted", "source": "Maya"},
    {"id": "frizz", "group": "Dynamics, fur and Bifrost", "label": "Frizz", "view": "Stray hairs", "values": "0 to 5", "source": "Maya"},
    {"id": "hairColor", "group": "Dynamics, fur and Bifrost", "label": "Hair color", "view": "Melanin value", "values": "0 to 1", "source": "Maya"},
    {"id": "hairShine", "group": "Dynamics, fur and Bifrost", "label": "Shine", "view": "Hair sheen", "values": "dull, sheen, glossy", "source": "Maya"},
    {"id": "furResponse", "group": "Dynamics, fur and Bifrost", "label": "Fur reacts to", "view": "What moves the fur", "values": "nothing, wind, the body, both", "source": "Maya"},
    {"id": "furLag", "group": "Dynamics, fur and Bifrost", "label": "Fur lag", "view": "Beats the fur trails the body", "values": "beats", "source": "Maya"},
    {"id": "element", "group": "Dynamics, fur and Bifrost", "label": "Element", "view": "Which simulated element is present", "values": "water, smoke, fire, sand, snow", "source": "Maya"},
    {"id": "density", "group": "Dynamics, fur and Bifrost", "label": "Thickness", "view": "Volume density", "values": "wisp, plume, wall", "source": "Maya"},
    {"id": "growth", "group": "Dynamics, fur and Bifrost", "label": "Growth", "view": "Whether the element is growing", "values": "shrinking, steady, building", "source": "Maya"},
    {"id": "curl", "group": "Dynamics, fur and Bifrost", "label": "Curl", "view": "Swirl in smoke or water", "values": "0 to 5", "source": "Maya"},
    {"id": "splash", "group": "Dynamics, fur and Bifrost", "label": "Splash", "view": "Liquid response to an object", "values": "none, drip, burst", "source": "Maya"},
    {"id": "scatter", "group": "Dynamics, fur and Bifrost", "label": "Scattered things", "view": "Leaves, debris or crowd per area", "values": "0 to 5", "source": "Maya"},
    {"id": "fireLight", "group": "Dynamics, fur and Bifrost", "label": "Fire lights the scene", "view": "Fire or glow feeding the lighting", "values": "no, flicker, floods", "source": "Maya"},
    {"id": "repeatInFrame", "group": "Dynamics, fur and Bifrost", "label": "Repetition in frame", "view": "Rows of the same thing (MASH arrays)", "values": "0 to 5", "source": "Maya"},
    {"id": "setting", "group": "Place", "label": "Setting", "view": "Location per scene", "values": "kitchen, lab, courtyard, wall, commute", "source": "board, chat"},
    {"id": "intExt", "group": "Place", "label": "Interior or exterior", "view": "Inside or outside", "values": "int, ext", "source": "board"},
    {"id": "envMotion", "group": "Place", "label": "Motion of the environment", "view": "What the room does", "values": "still, wind, crowd, water, transit", "source": "board"},
    {"id": "temperature", "group": "Place", "label": "Temperature", "view": "How hot the place feels", "values": "cold, mild, hot", "source": "board"},
    {"id": "weather", "group": "Place", "label": "Weather", "view": "Weather per scene", "values": "clear, rain, dust", "source": "board"},
    {"id": "scale", "group": "Place", "label": "Scale of the place", "view": "Size of the space", "values": "closet, hall, city", "source": "board"},
    {"id": "peopleCount", "group": "People", "label": "Number of people", "view": "Bodies in frame", "values": "1 to 8", "source": "board"},
    {"id": "blocking", "group": "People", "label": "Where they stand", "view": "Floor-plan shape", "values": "line, triangle, depth, one seated", "source": "board"},
    {"id": "eyeline", "group": "People", "label": "Eyelines", "view": "Who looks at whom", "values": "pairs", "source": "board"},
    {"id": "focus", "group": "People", "label": "Who is sharp", "view": "The sharp subject", "values": "face, hand, object, door", "source": "board"},
    {"id": "look", "group": "People", "label": "Look of the actor", "view": "Wardrobe and face as the camera reads them", "values": "notes as tags", "source": "board"},
    {"id": "volume", "group": "Sound", "label": "Volume of the lines", "view": "Loudness curve of speech", "values": "1 to 5", "source": "board, chat"},
    {"id": "dynamicRange", "group": "Sound", "label": "Dynamic range of the lines", "view": "Gap between quiet and loud lines", "values": "narrow, wide", "source": "board"},
    {"id": "rangeChanges", "group": "Sound", "label": "How often the range changes", "view": "Frequency of loud to soft swings", "values": "rare, every other, every line", "source": "board"},
    {"id": "pace", "group": "Sound", "label": "Pace", "view": "Speed of speech against the hold", "values": "words per second", "source": "board"},
    {"id": "silence", "group": "Sound", "label": "Silence length", "view": "Gaps nobody fills", "values": "seconds", "source": "board, music"},
    {"id": "breath", "group": "Sound", "label": "Breathing and speaking", "view": "Breath placement", "values": "breath then speak, speak on the breath, ignore", "source": "board"},
    {"id": "eating", "group": "Sound", "label": "Eating and speaking", "view": "The mouth's job", "values": "none, eat then speak, speak while eating", "source": "board"},
    {"id": "musicCue", "group": "Sound", "label": "Score", "view": "Where music plays and how loud", "values": "off, under, featured", "source": "new"},
    {"id": "soundDensity", "group": "Sound", "label": "Sound density", "view": "Layers of sound at once", "values": "1 to 6", "source": "music"},
    {"id": "soundToCut", "group": "Sound", "label": "Sound against the cut", "view": "Sound leading or trailing the picture cut", "values": "J-cut, L-cut, hard", "source": "new"},
    {"id": "sceneRate", "group": "Edit and structure", "label": "Scene change rate", "view": "How often the scene changes, the film's harmonic rhythm", "values": "scenes per 10 minutes", "source": "music"},
    {"id": "phraseScheme", "group": "Edit and structure", "label": "Sequence lengths", "view": "Lengths of runs of related shots, like 4+4 or 3+3+2", "values": "shots per phrase", "source": "music"},
    {"id": "sceneEntry", "group": "Edit and structure", "label": "How a scene begins", "view": "The film's anacrusis", "values": "in action, on a line, establishing, sound first", "source": "music"},
    {"id": "transition", "group": "Edit and structure", "label": "Transition", "view": "How each boundary is crossed", "values": "cut, match cut, smash cut, dissolve, sound bridge", "source": "music"},
    {"id": "callResponse", "group": "Edit and structure", "label": "Call and response", "view": "Who answers whom across cuts", "values": "pairs and lag in beats", "source": "music"},
    {"id": "repetition", "group": "Edit and structure", "label": "Repetition scheme", "view": "How many times an image returns before it varies", "values": "count", "source": "music"},
    {"id": "hook", "group": "Edit and structure", "label": "Signature image", "view": "Where the memorable image or line recurs", "values": "beat positions", "source": "music"},
    {"id": "contrastMap", "group": "Edit and structure", "label": "Contrast map", "view": "A:B pairs the film keeps, like quiet:loud or sparse:dense", "values": "pairs", "source": "music"},
    {"id": "tensionCurve", "group": "Edit and structure", "label": "Tension", "view": "Rising and released tension", "values": "0 to 5", "source": "music"},
    {"id": "energyArc", "group": "Edit and structure", "label": "Energy", "view": "Build, drop and plateau across the work", "values": "0 to 5", "source": "music"},
    {"id": "visualDensity", "group": "Edit and structure", "label": "Visual density", "view": "Elements on screen at once", "values": "1 to 10", "source": "music"},
    {"id": "pedal", "group": "Edit and structure", "label": "Constant", "view": "One element held steady while everything else changes", "values": "which element, how long", "source": "music"},
    {"id": "psychOut", "group": "Edit and structure", "label": "Psych-out shift", "view": "A shift of place or tone that snaps back within a beat, against a real shift that stays", "values": "psych-out, real", "source": "chat"},
    {"id": "cutArticulation", "group": "Edit and structure", "label": "Cut articulation", "view": "Clipped cuts against long overlaps, staccato against legato", "values": "0 clipped to 5 overlapping", "source": "music"},
    {"id": "operatorFeel", "group": "Edit and structure", "label": "Operator feel", "view": "Small timing drift in camera and cuts, the humanized feel", "values": "0 to 5", "source": "music"},
    {"id": "motifShape", "group": "Edit and structure", "label": "Motif shape", "view": "The rise and fall of a visual motif, such as size, height or brightness, across its returns", "values": "contour", "source": "music"},
    {"id": "panelCount", "group": "Comic", "label": "Panels", "view": "Panels per strip or page", "values": "count", "source": "board"},
    {"id": "gutter", "group": "Comic", "label": "Gutter", "view": "Time skipped between panels", "values": "none, beat, scene", "source": "board"},
    {"id": "balloon", "group": "Comic", "label": "Balloon against caption", "view": "Speech or narration", "values": "balloon, caption, both", "source": "board"},
    {"id": "panelSize", "group": "Comic", "label": "Panel size", "view": "Share of the page each panel takes", "values": "0 to 100 percent", "source": "new"},
    {"id": "panelBreak", "group": "Comic", "label": "Breaking the frame", "view": "Figures crossing panel borders", "values": "none, edge, splash", "source": "new"},
    {"id": "textDensity", "group": "Comic", "label": "Words per panel", "view": "Lettering load", "values": "words", "source": "new"},
    {"id": "soundLettering", "group": "Comic", "label": "Sound effects", "view": "Drawn sound words", "values": "none, small, page-sized", "source": "new"},
    {"id": "pageTurn", "group": "Comic", "label": "Page-turn reveal", "view": "What waits on the next page", "values": "none, reveal, cliffhanger", "source": "new"},
    {"id": "mains", "group": "Story", "label": "Featured mains", "view": "Mains followed this hour", "values": "2 to 4", "source": "board"},
    {"id": "groups", "group": "Story", "label": "Groups in the hour", "view": "Companies of people", "values": "1, 2", "source": "board"},
    {"id": "exit", "group": "Story", "label": "Exit", "view": "How a main leaves", "values": "stay, leave, die", "source": "board"},
    {"id": "featureRate", "group": "Story", "label": "How often a main is in the season", "view": "Hours per main", "values": "count", "source": "board"},
    {"id": "intercut", "group": "Story", "label": "Cross-cutting", "view": "Switches between storylines", "values": "switches per scene", "source": "new"},
    {"id": "reveal", "group": "Story", "label": "Reveal timing", "view": "When the audience learns a fact relative to the characters", "values": "before, with, after", "source": "new"},
    {"id": "povSwitch", "group": "Story", "label": "Story point of view", "view": "Whose story each scene tells", "values": "person", "source": "new"},
    {"id": "sceneLength", "group": "Story", "label": "Scene length", "view": "Minutes per scene", "values": "minutes", "source": "new"},
    {"id": "sceneShapes", "group": "Scene memory", "label": "Shapes in the scene", "view": "A simple map of big shapes by frame position", "values": "shape + left, center, right, near, far", "source": "chat"},
    {"id": "vocalTone", "group": "Scene memory", "label": "Tone of the line", "view": "What the voice does through the line", "values": "flat, rising, falling, breaking, whispered, shouted", "source": "chat"},
    {"id": "toneArc", "group": "Scene memory", "label": "Where the tone sits in the story", "view": "Vocal tone placed on the film's timeline", "values": "act and minute", "source": "chat"},
    {"id": "timePerCharacter", "group": "Scene memory", "label": "Time on each character", "view": "Share of screen time per person", "values": "percent per person", "source": "chat"},
    {"id": "actionCutRate", "group": "Scene memory", "label": "Cut rate in action", "view": "Cuts per minute during action beats only", "values": "cuts per minute", "source": "chat"},
    {"id": "emotion", "group": "Scene memory", "label": "Emotion of the beat", "view": "The emotion label that drives the emotion map", "values": "loving, joyful, curious, melancholy, anxious, fearful, angry, triumphant, absurd, dreamlike", "source": "chat"},
  ],
  moves: [
    {"id": "devAugment", "label": "Augmentation", "does": "The same action or image, held longer or slowed", "source": "music"},
    {"id": "devDiminish", "label": "Diminution", "does": "The same action, faster or cut shorter", "source": "music"},
    {"id": "devInvert", "label": "Inversion", "does": "Flipped: high angle becomes low, approach becomes retreat, warm becomes cold", "source": "music"},
    {"id": "devRetrograde", "label": "Retrograde", "does": "The shots of a sequence in reverse order", "source": "music"},
    {"id": "devFragment", "label": "Fragmentation", "does": "Only one piece of the motif returns, such as just the hand or just the sound", "source": "music"},
    {"id": "devSequence", "label": "Sequence", "does": "The same pattern repeated in a new place or with a new person", "source": "music"},
    {"id": "devAddSpace", "label": "Add space", "does": "Silence or empty frame inserted inside the motif", "source": "music"},
    {"id": "devModulate", "label": "Modulation", "does": "The motif moves to a new place, light or tone and stays there", "source": "music, chat"},
    {"id": "devPsychOut", "label": "Psych-out", "does": "The motif shifts away for a beat and snaps back", "source": "chat"},
    {"id": "devSwap", "label": "Slice swap", "does": "One curiosity taken from another work while the rest stays ours", "source": "chat"},
  ],
  suites: [
    {"label": "Coverage", "sets": "angleFamily coverage, angleChange on the line, angleCount 4", "source": "board"},
    {"label": "Oner", "sets": "angleFamily oner, cameraCarry smooth, cameraMove track, angleChange locked", "source": "board"},
    {"label": "Handheld hunt", "sets": "cameraCarry handheld, angleFamily handheld, angleCount 6, moveSpeed 4", "source": "board"},
    {"label": "Smooth push", "sets": "cameraCarry smooth, cameraMove push in, moveSpeed 1", "source": "board"},
    {"label": "Quiet confession", "sets": "volume 1, breath then speak, cameraCarry smooth, cameraMove push in", "source": "board"},
    {"label": "Object insert", "sets": "objectPath lift, objectEnter enters, moveFollows object, cameraMove push in", "source": "board"},
    {"label": "Crossing", "sets": "characterPath cross, characterToLens across, cameraCarry locked", "source": "board"},
    {"label": "Two-person hour", "sets": "mains 2, groups 1, peopleCount 2", "source": "board"},
    {"label": "Loving camera", "sets": "moveTemper 1, cameraCarry smooth, moveSpeed 1, softness soft, depthOfField shallow", "source": "chat"},
    {"label": "Aggressive camera", "sets": "moveTemper 5, cameraCarry handheld, cutRate high, lensLength wide, softness hard", "source": "chat"},
    {"label": "Follows the voice", "sets": "moveToVolume moves on loud, moveOn line, dynamicRange wide", "source": "chat"},
    {"label": "Snappy cartoon", "sets": "stepping twos, anticipation big, overshoot bounce, squash 4", "source": "Maya"},
    {"label": "Grounded realism", "sets": "stepping ones, anticipation small, overshoot settle, overlap hair", "source": "Maya"},
    {"label": "Noir", "sets": "softness hard, contrast 4, lightShape blinds, atmosphere haze, valueKey low", "source": "Maya"},
    {"label": "Golden hour", "sets": "colorTemp 3200, key back, rim strong, softness soft", "source": "Maya"},
    {"label": "Comic ink", "sets": "renderStyle toon, lineWeight heavy, saturation 2", "source": "Maya"},
    {"label": "Wet night", "sets": "wetness soaked, gloss mirror, practicalInFrame yes, weather rain", "source": "Maya"},
    {"label": "Storm", "sets": "windForce 5, turbulence 4, clothResponse flutter, furResponse wind", "source": "Maya"},
    {"label": "Hearth", "sets": "element fire, growth steady, fireLight flicker, colorTemp 2700", "source": "Maya"},
    {"label": "Brawl", "sets": "impacts 6, breakage shatters, cameraCarry handheld, cutRate high", "source": "Maya"},
    {"label": "Build", "sets": "energyArc rising, cutRate rising, density rising, musicCue featured", "source": "music"},
    {"label": "Drop", "sets": "energyArc falls to 1, silence long, density 1, cameraCarry locked", "source": "music"},
    {"label": "Breathing room", "sets": "silence long, emptySpace high, shotDuration long, devAddSpace", "source": "music"},
    {"label": "Signature return", "sets": "hook, repetition, motifShape, devFragment", "source": "music"},
  ],
  proximities: [
    {"when": "cameraCarry is handheld", "then": "gesture grows", "within": 2, "source": "board"},
    {"when": "shotSize becomes close", "then": "volume drops", "within": 1, "source": "board"},
    {"when": "characterPath is approach", "then": "cameraMove push in", "within": 2, "source": "board"},
    {"when": "objectEnter is enters", "then": "shotSize becomes insert", "within": 1, "source": "board"},
    {"when": "volume rises", "then": "moveSpeed rises", "within": 0, "source": "chat"},
    {"when": "the action turns aggressive", "then": "moveTemper rises and cameraCarry goes handheld", "within": 1, "source": "chat"},
    {"when": "a line ends", "then": "the angle changes", "within": 0, "source": "chat"},
    {"when": "leadPart is eyes", "then": "head turns, then the body", "within": 1, "source": "Maya"},
    {"when": "the character stops", "then": "overlap, furLag and clothResponse settle, in that order", "within": 2, "source": "Maya"},
    {"when": "a practical switches on", "then": "key moves to it", "within": 0, "source": "Maya"},
    {"when": "weather turns to rain", "then": "wetness soaked, clump matted, gloss mirror", "within": 2, "source": "Maya"},
    {"when": "growth is building on fire", "then": "colorTemp warms and contrast rises", "within": 0, "source": "Maya"},
    {"when": "an impact lands", "then": "overshoot bounces and cameraShake rises", "within": 0, "source": "Maya"},
    {"when": "renderStyle becomes toon", "then": "lighting flattens and lineWeight rises", "within": 0, "source": "Maya"},
    {"when": "a scene boundary", "then": "transition marks it with a sound bridge or match cut", "within": 0, "source": "music"},
    {"when": "a motif has returned 3 times", "then": "the next return varies (devFragment or devInvert)", "within": 0, "source": "music"},
    {"when": "tensionCurve peaks", "then": "silence follows", "within": 1, "source": "music"},
    {"when": "a psych-out shift", "then": "the scene snaps back to its home place or tone", "within": 1, "source": "chat"},
    {"when": "energyArc drops", "then": "shotDuration lengthens", "within": 2, "source": "music"},
    {"when": "suite Build", "then": "suite Drop", "within": 4, "source": "suite"},
    {"when": "suite Aggressive camera", "then": "suite Quiet confession", "within": 6, "source": "suite"},
    {"when": "suite Storm", "then": "suite Breathing room", "within": 8, "source": "suite"},
  ],
};
/* Values a study records per beat. The doc gives some values as units (mm, K, cuts per minute);
   a beat stores a coarse choice instead, so it can be read off one frame. A tag is a short free word. */
const LIBRARY_VALUES = {
  lensLength: ["wide", "normal", "long"],
  depthOfField: ["shallow", "medium", "deep"],
  motionBlur: ["none", "light", "heavy"],
  emptySpace: ["little", "some", "most"],
  speedRamp: ["slow", "normal", "fast", "ramp"],
  cutRate: ["slow", "medium", "fast"],
  shotDuration: ["short", "medium", "long"],
  silence: ["none", "short", "long"],
  pace: ["slow", "medium", "fast"],
  hairColor: ["light", "medium", "dark"],
  sceneRate: ["slow", "medium", "fast"],
  sceneLength: ["short", "medium", "long"],
  motifShape: ["rises", "falls", "arch", "flat"],
  hook: ["no", "yes"],
  panelSize: ["small", "medium", "large", "splash"],
  textDensity: ["none", "few", "many"],
  toneArc: ["opening", "rising", "midpoint", "climax", "ending"],
  colorTemp: ["warm practical", "cold day", "mixed"],
  aspect: ["1.33", "1.85", "2.39", "custom"],
  faceIntensity: { min: 0, max: 5 },
  settleTime: { min: 0, max: 4 },
  furLag: { min: 0, max: 4 },
  repetition: { min: 0, max: 8 },
  panelCount: { min: 1, max: 8 },
  intercut: { min: 0, max: 8 },
  actionCutRate: { min: 0, max: 8 },
  contrast: { min: 0, max: 6 },
  gesture: { min: 0, max: 5 },
  sceneShapes: "tag",
  pedal: "tag",
};

/* Merge the library into the working catalog: new rows are added, existing rows keep their
   controls and gain the doc's view and source. */
(function () {
  const have = Object.fromEntries(CURIOSITIES.map((c) => [c.id, c]));
  function valuesFor(row) {
    const o = LIBRARY_VALUES[row.id];
    if (o === "tag") return { kind: "tag" };
    if (Array.isArray(o)) return { kind: "select", options: o };
    if (o) return { kind: "range", min: o.min, max: o.max };
    const v = row.values;
    const range = v.match(/^(\d+)\D*? to (\d+)(?:\s+[a-z ]+)?$/i);
    if (range && !/\d/.test(v.slice(range.index + range[0].length))) return { kind: "range", min: Number(range[1]), max: Number(range[2]) };
    if (v.includes(",") && !/\d/.test(v)) return { kind: "select", options: v.split(",").map((x) => x.trim()) };
    return { kind: "tag" };
  }
  LIBRARY.curiosities.forEach((row) => {
    const c = have[row.id];
    if (c) {
      c.view = row.view;
      c.source = row.source;
      if (!c.kind) Object.assign(c, valuesFor(row));
      return;
    }
    CURIOSITIES.push(Object.assign({ id: row.id, group: row.group, label: row.label, note: row.view, view: row.view, source: row.source }, valuesFor(row)));
  });
})();
