/* Writes LANGUAGE-REVIEW.md: every writing-only curiosity with its sliders, marked keep, for Jeremy to review.
   Change a row's keep to drop or change and say what. Run: node apps/curiosities-writing/tools/review-list.js */
const fs = require("fs");
const path = require("path");
const DB = require("../../curiosities/data/load-db.js");
require("../../curiosities/data/writing/db-writing-language.js");
require("../../curiosities/data/writing/db-writing-ladder.js");
require("../../curiosities/data/writing/db-writing-movement.js");
require("../../curiosities/data/writing/db-writing-blocks.js");
require("../../curiosities/data/writing/db-writing-forms.js");
require("../../curiosities/data/writing/db-writing-dialogue.js");

const SHARED = ["narration", "byCharacter", "byVoice", "change", "often", "place", "spacing", "gap", "subject", "amount", "push", "pointsAhead", "themeLink"];
const ws = Object.fromEntries(DB.data.workspaces.map((w) => [w.id, w.label]));
const rows = DB.data.curiosities.filter((r) => (r.tags || []).includes("writing-only"));
let out = `# Language curiosities: review list\n\n${rows.length} writing-only curiosities (generated by tools/review-list.js). Every row is marked **keep**; change it to **drop** or **change** and say what.\n\n`;
out += "Every countable one (marked ★) also has: how often, where in the sentence, spacing, gap between two, what it is about. Every row also has: narration or dialogue, spread across characters, which narrative voice, change from sentence to sentence.\n";
let n = 0;
Object.keys(ws).forEach((w) => {
  const here = rows.filter((r) => r.workspace === w);
  if (!here.length) return;
  out += `\n## ${ws[w]}\n\n| # | Curiosity | What it is | Its own sliders | Keep? |\n| --- | --- | --- | --- | --- |\n`;
  here.forEach((r) => {
    const own = r.sliders.filter((s) => !SHARED.includes(s.id) || s.id === r.main).map((s) => s.label).join("; ");
    const star = r.sliders.some((s) => s.id === "spacing") ? " ★" : "";
    out += `| ${++n} | ${r.label}${star} | ${r.plain.replace(/\|/g, "/")} | ${own} | keep |\n`;
  });
});
const mine = (k) => DB.data[k].filter((r) => (r.tags || []).includes("writing-only"));
const label = (id) => (DB.get("curiosity", id) || { label: id }).label;
let k = 0;
out += `\n# The ladder\n\nSuites go together; proximities are tangentially related and set nothing off; catalysts (sparks) set something off within a few sentences; elixirs fire only when every spark lines up, like tumblers in a lock. Numbers carry on from the curiosities, so you can name any row by number.\n`;
out += `\n## Suites (curiosities that go together)\n\n| # | Suite | What it is | Members | Keep? |\n| --- | --- | --- | --- | --- |\n`;
mine("suites").forEach((r) => (out += `| ${n + ++k} | ${r.label} | ${r.plain} | ${r.members.map((x) => label(x.curiosity) + " " + x.value).join("; ")} | keep |\n`));
out += `\n## Proximities (tangentially related)\n\n| # | One | The other | How close (0 to 100) | Why | Keep? |\n| --- | --- | --- | --- | --- | --- |\n`;
DB.writingProximities.forEach((p) => (out += `| ${n + ++k} | ${label(p.a)} | ${label(p.b)} | ${p.how} | ${p.why} | keep |\n`));
out += `\n## Catalysts (sparks: when this, then that)\n\n| # | Catalyst | Within (sentences) | How often | Keep? |\n| --- | --- | --- | --- | --- |\n`;
mine("proximities").forEach((r) => (out += `| ${n + ++k} | ${r.label} | ${r.within} | ${r.often}% | keep |\n`));
out += `\n## Elixirs (every spark must line up)\n\n| # | Elixir | What it is | The sparks (tumblers) | Keep? |\n| --- | --- | --- | --- | --- |\n`;
mine("proximitySuites").forEach((r) => (out += `| ${n + ++k} | ${r.label} | ${r.plain} | ${r.members.map((id) => DB.get("proximity", id).label).join("; ")} | keep |\n`));
n += k;
fs.writeFileSync(path.join(__dirname, "..", "LANGUAGE-REVIEW.md"), out);
console.log("Wrote LANGUAGE-REVIEW.md: " + n + " rows");
