/* Writes LANGUAGE-REVIEW.md: every writing-only curiosity with its sliders, marked keep, for Jeremy to review.
   Change a row's keep to drop or change and say what. Run: node apps/curiosities-writing/tools/review-list.js */
const fs = require("fs");
const path = require("path");
const DB = require("../../curiosities/data/load-db.js");
require("../data/db-writing-language.js");

const SHARED = ["narration", "byCharacter", "byVoice", "change", "often", "place", "spacing", "gap", "subject", "amount", "push", "pointsAhead", "themeLink"];
const ws = Object.fromEntries(DB.data.workspaces.map((w) => [w.id, w.label]));
const rows = DB.data.curiosities.filter((r) => (r.tags || []).includes("writing-only"));
let out = `# Language curiosities: review list\n\n${rows.length} writing-only curiosities (generated by tools/review-list.js). Every row is marked **keep**; change it to **drop** or **change** and say what.\n\n`;
out += "Every countable one (marked ★) also has: how often, where in the sentence, spacing, gap between two, what it is about. Every row also has: narration or dialogue, spread across characters, which narrative voice, change from sentence to sentence.\n";
let n = 0;
Object.keys(ws).forEach((w) => {
  const here = rows.filter((r) => r.workspace === w);
  if (!here.length) return;
  out += `\n## ${ws[w]}\n\n| # | Curiosity | What it is | Its own sliders | Keep? |\n| --- | --- | --- | --- | --- |\n`;
  here.forEach((r) => {
    const own = r.sliders.filter((s) => !SHARED.includes(s.id) || s.id === r.main).map((s) => s.label).join("; ");
    const star = r.sliders.some((s) => s.id === "spacing") ? " ★" : "";
    out += `| ${++n} | ${r.label}${star} | ${r.plain.replace(/\|/g, "/")} | ${own} | keep |\n`;
  });
});
fs.writeFileSync(path.join(__dirname, "..", "LANGUAGE-REVIEW.md"), out);
console.log("Wrote LANGUAGE-REVIEW.md: " + n + " rows");
