/* Builds the VCV Rack side of the bridge from the curiosity database.

   node vcv/tools/make-vcv.js

   Writes:
   - vcv/curiosity-jacks.js    the jack list for the app (window.CURIOSITY_VCV): every curiosity, suite, proximity
                               and proximity suite gets one jack, that is one MIDI channel and CC number.
   - vcv/curiosity-jacks.json  the same list as JSON, for other tools.
   - vcv/rack/<workspace>.vcvs one VCV Rack selection file per workspace: a Notes module naming every jack, an LFO
                               already patched into the first jack, and as many CV-CC modules as the workspace needs.
   - vcv/rack/all-curiosities.vcvs  every workspace, one rack row each.
   - vcv/rack/focus-lanes.vcvs the Focus module: 16 jacks that drive the sliders (lanes) of whichever item is in focus.

   A .vcvs file is VCV Rack 2's "module selection" format (File > Import selection). Its shape follows Rack's own
   source: src/app/RackWidget.cpp (selectionToJson), src/core/CV_MIDICC.cpp ("ccs", "midi"), src/midi.cpp
   ("driver", "deviceName", "channel"), Fundamental's LFO.cpp (outputs: sine 0; Offset switch defaults to unipolar). */
const fs = require("fs");
const path = require("path");
const DB = require("../../data/load-db.js");

const OUT = path.join(__dirname, "..");
const JACKS_PER_MODULE = 16; /* one VCV CV-CC module */
const MODULES_PER_CHANNEL = 7; /* 7 x 16 = 112 CCs, numbers 1 to 112, clear of 0 (bank select) and 120-127 (channel mode) */
const FOCUS_CHANNEL = 16; /* MIDI channel 16 is kept for the Focus module */
const MODULES_PER_PORT = (FOCUS_CHANNEL - 1) * MODULES_PER_CHANNEL; /* 105 modules (1,680 CCs) fit on one MIDI port */
const MAX_PORTS = 4; /* port 1 is the first virtual MIDI cable; ports 2 and up are more cables named "... 2", "... 3" */

const data = DB.toJSON();
const LEVELS = [
  ["curiosities", "curiosity"],
  ["suites", "suite"],
  ["proximities", "proximity"],
  ["proximitySuites", "proximitySuite"],
];

/* Each workspace starts on a fresh module, so a workspace's jacks sit together in the rack. */
const jacks = [];
const groups = [];
let moduleIndex = 0;
data.workspaces.forEach((w) => {
  const items = [];
  LEVELS.forEach(([list, level]) => data[list].filter((x) => x.workspace === w.id).forEach((x) => items.push(Object.assign({ level }, x))));
  if (!items.length) return;
  const g = { workspace: w.id, label: w.label, modules: [] };
  for (let i = 0; i < items.length; i += JACKS_PER_MODULE) {
    const m = moduleIndex++;
    /* Port 1 keeps the first 105 modules exactly where they were; later modules go on to a second cable. */
    const port = Math.floor(m / MODULES_PER_PORT) + 1;
    const channel = Math.floor((m % MODULES_PER_PORT) / MODULES_PER_CHANNEL) + 1;
    if (port > MAX_PORTS) throw new Error("Out of MIDI ports: raise MAX_PORTS (and add a cable)");
    const first = ((m % MODULES_PER_PORT) % MODULES_PER_CHANNEL) * JACKS_PER_MODULE + 1;
    const mod = { index: m, port, channel, ccs: [], items: [] };
    items.slice(i, i + JACKS_PER_MODULE).forEach((x, j) => {
      const cc = first + j;
      const key = DB.key(x);
      mod.ccs.push(cc);
      mod.items.push(x);
      jacks.push({ key, port, channel, cc, label: x.label, level: x.level, workspace: w.id, module: m + 1, jack: j + 1 });
    });
    while (mod.ccs.length < JACKS_PER_MODULE) mod.ccs.push(-1); /* unused jacks send nothing */
    g.modules.push(mod);
  }
  groups.push(g);
});

/* ---------- the app side ---------- */
const bank = {
  made: "vcv/tools/make-vcv.js from the curiosity database",
  counts: DB.counts(),
  focus: { channel: FOCUS_CHANNEL, ccs: Array.from({ length: 16 }, (_, i) => i + 1) },
  jacks,
};
fs.writeFileSync(path.join(OUT, "curiosity-jacks.json"), JSON.stringify(bank, null, 1) + "\n");
fs.writeFileSync(
  path.join(OUT, "curiosity-jacks.js"),
  "/* Generated by vcv/tools/make-vcv.js: do not edit by hand. One jack (MIDI channel and CC) per curiosity, suite,\n" +
    "   proximity and proximity suite, plus the Focus module's 16 jacks on channel " + FOCUS_CHANNEL + ". Read by vcv/bridge.js.\n" +
    "   Each jack is [key, channel, cc, label, workspace, module, jack], with an 8th entry for MIDI port 2 and up. */\n" +
    "window.CURIOSITY_VCV = " + JSON.stringify({ focus: bank.focus, jacks: jacks.map((j) => [j.key, j.channel, j.cc, j.label, j.workspace, j.module, j.jack].concat(j.port > 1 ? [j.port] : [])) }) + ";\n"
);

/* ---------- the Rack side ---------- */
const SHORT = { curiosity: "", suite: "suite: ", proximity: "pair: ", proximitySuite: "pairs: " };
let nextId = 1;
const cvcc = (channel, ccs, x, y) => ({ id: nextId++, plugin: "Core", model: "CV-CC", data: { ccs, midi: { channel: channel - 1 } }, pos: [x, y] });
const notes = (text, x, y) => ({ id: nextId++, plugin: "Core", model: "Notes", data: { text }, pos: [x, y] });
const lfo = (x, y) => ({ id: nextId++, plugin: "Fundamental", model: "LFO", pos: [x, y] });
const W = { notes: 15, cvcc: 8, lfo: 9 }; /* widths in rack units (HP), with a little room */

function row(g, y, withLfo) {
  const mods = [];
  const cables = [];
  let x = 0;
  const lines = [g.label.toUpperCase(), "Patch any CV (0 to 10 V) into a jack. 0 V is the item's From setting, 10 V its To.", ""];
  g.modules.forEach((m, n) => {
    lines.push(`CV-CC ${n + 1}: ${m.port > 1 ? `PORT ${m.port} (your second cable), ` : ""}MIDI channel ${m.channel}, CC ${m.ccs[0]} to ${m.ccs[m.items.length - 1]}`);
    m.items.forEach((it, j) => lines.push(`  ${String(j + 1).padStart(2)} ${SHORT[it.level]}${it.label}`));
  });
  mods.push(notes(lines.join("\n"), x, y));
  x += W.notes;
  let l = null;
  if (withLfo) {
    l = lfo(x, y);
    mods.push(l);
    x += W.lfo;
  }
  g.modules.forEach((m, n) => {
    const c = cvcc(m.channel, m.ccs, x, y);
    mods.push(c);
    x += W.cvcc;
    if (l && n === 0) cables.push({ id: nextId++, outputModuleId: l.id, outputId: 0, inputModuleId: c.id, inputId: 0, color: "#f3374b" });
  });
  return { mods, cables };
}

fs.mkdirSync(path.join(OUT, "rack"), { recursive: true });
const all = { modules: [], cables: [] };
groups.forEach((g, i) => {
  nextId = 1;
  const one = row(g, 0, true);
  fs.writeFileSync(path.join(OUT, "rack", g.workspace + ".vcvs"), JSON.stringify({ modules: one.mods, cables: one.cables }, null, 1) + "\n");
});
nextId = 1;
groups.forEach((g, i) => {
  const r = row(g, i, false);
  all.modules.push(...r.mods);
});
fs.writeFileSync(path.join(OUT, "rack", "all-curiosities.vcvs"), JSON.stringify(all, null, 1) + "\n");

nextId = 1;
const focusText = [
  "FOCUS: SLIDERS OF ONE ITEM",
  "In the app, click Focus on any automation module (or call CurioVCV.focus(\"c:music\")).",
  "These 16 jacks then drive that item's sliders, in the order its module lists them:",
  "jack 1 its main slider, jack 2 the next, and so on.",
  `MIDI channel ${FOCUS_CHANNEL}, CC 1 to 16.`,
].join("\n");
const focus = { modules: [notes(focusText, 0, 0), lfo(W.notes, 0), cvcc(FOCUS_CHANNEL, bank.focus.ccs, W.notes + W.lfo, 0)], cables: [] };
focus.cables.push({ id: nextId++, outputModuleId: focus.modules[1].id, outputId: 0, inputModuleId: focus.modules[2].id, inputId: 0, color: "#f3374b" });
fs.writeFileSync(path.join(OUT, "rack", "focus-lanes.vcvs"), JSON.stringify(focus, null, 1) + "\n");

const ports = Math.max(...jacks.map((j) => j.port));
const lastChannel = Math.max(...jacks.filter((j) => j.port === ports).map((j) => j.channel));
console.log(`${jacks.length} jacks on ${moduleIndex} CV-CC modules, ${ports > 1 ? ports + " MIDI ports (last one up to channel " + lastChannel + ")" : "MIDI channels 1 to " + lastChannel}, focus on ${FOCUS_CHANNEL}; ${groups.length} workspace files; room for ${MAX_PORTS * MODULES_PER_PORT - moduleIndex} more modules`);
