/* Generates the Curiosities VCV Rack plugin (stage 2 in vcv/SPEC.md) from the jack list.

   node vcv/tools/make-vcv.js      (first: the jack list)
   node vcv/tools/make-plugin.js   (then: vcv/plugin/)

   One Rack module per group of 16 jacks, the same groups as stage 1's CV-CC modules (so a stage 1 patch and a
   stage 2 patch send the same MIDI channel and CC numbers and the app's bridge needs no change). Each panel
   prints every item's name beside its jack. Plus a Focus module (channel 16) for one item's sliders.

   Build it with the VCV Rack SDK (https://vcvrack.com/manual/PluginDevelopmentTutorial):
     cd vcv/plugin && make install RACK_DIR=<path to Rack-SDK>
   The code uses Rack 2's plugin API (Module, configInput, midi::Output, appendMidiMenu, nanovg labels) and plain UDP
   sockets for OSC to the desktop app (right-click: Send by OSC). It has
   not been compiled yet: the SDK download (vcvrack.com) is blocked where it was written. */
const fs = require("fs");
const path = require("path");

const VCV = path.join(__dirname, "..");
const OUT = path.join(VCV, "plugin");
const bank = require(path.join(VCV, "curiosity-jacks.json"));
const WS = Object.fromEntries(require("../../data/load-db.js").toJSON().workspaces.map((w) => [w.id, w.label]));

/* Group the jacks by stage 1 module number, keeping order. */
const mods = [];
bank.jacks.forEach((j) => {
  let m = mods.find((x) => x.n === j.module);
  if (!m) mods.push((m = { n: j.module, channel: j.channel, workspace: j.workspace, items: [] }));
  m.items.push(j);
});
/* A workspace with several modules numbers them: "Comedy 1", "Comedy 2"... */
mods.forEach((m) => {
  const same = mods.filter((x) => x.workspace === m.workspace);
  m.title = WS[m.workspace] + (same.length > 1 ? " " + (same.indexOf(m) + 1) : "");
  m.slug = "Curio-" + m.workspace + (same.length > 1 ? "-" + (same.indexOf(m) + 1) : "");
});

const cstr = (s) => JSON.stringify(String(s)); /* a C++ string literal (JSON escaping is valid C++ for these) */
const HP = 16; /* panel width in rack units: room for a name beside each jack */
const LEVEL = { "c:": 0, "s:": 1, "p:": 2, "ps:": 3 };
const levelOf = (key) => LEVEL[key.slice(0, key.indexOf(":") + 1)];

fs.mkdirSync(path.join(OUT, "src"), { recursive: true });
fs.mkdirSync(path.join(OUT, "res"), { recursive: true });

/* ---------- plugin.json ---------- */
const manifest = {
  slug: "Curiosities",
  name: "Curiosities",
  version: "2.0.0",
  license: "proprietary",
  brand: "Curiosities",
  author: "Wish Myself Well",
  authorEmail: "",
  authorUrl: "",
  pluginUrl: "",
  manualUrl: "",
  sourceUrl: "",
  donateUrl: "",
  changelogUrl: "",
  modules: mods
    .map((m) => ({ slug: m.slug, name: m.title, description: `${m.items.length} curiosities, suites and pairs from ${WS[m.workspace]}, one jack each, sent to the Curiosities app as MIDI CC on channel ${m.channel}.`, tags: ["Controller", "MIDI"] }))
    .concat([{ slug: "Curio-Return", name: "Return", description: "Place right of any Curiosities module: 16 outputs carry its items' current values back from the desktop app (OSC, UDP 7001) as 0 to 10 V.", tags: ["Controller", "Expander"] }])
    .concat([{ slug: "Curio-Focus", name: "Focus", description: "16 jacks for the sliders of the one item in focus in the Curiosities app (MIDI channel 16).", tags: ["Controller", "MIDI"] }]),
};
fs.writeFileSync(path.join(OUT, "plugin.json"), JSON.stringify(manifest, null, 2) + "\n");

/* ---------- Makefile ---------- */
fs.writeFileSync(
  path.join(OUT, "Makefile"),
  `# Generated by vcv/tools/make-plugin.js. Build: make install RACK_DIR=<path to Rack-SDK>
RACK_DIR ?= ../..
SOURCES += $(wildcard src/*.cpp)
DISTRIBUTABLES += res
DISTRIBUTABLES += $(wildcard LICENSE*)
include $(RACK_DIR)/plugin.mk
`
);

/* ---------- the jack table (generated) ---------- */
const banks = mods.map(
  (m, i) => `  { ${cstr(m.slug)}, ${cstr(m.title)}, ${m.channel}, ${m.items.length}, {\n${m.items.map((j) => `    { ${j.cc}, ${levelOf(j.key)}, ${cstr(j.label)}, ${cstr(j.key)} },`).join("\n")}\n  } },`
);
fs.writeFileSync(
  path.join(OUT, "src", "bank.hpp"),
  `// Generated by vcv/tools/make-plugin.js from vcv/curiosity-jacks.json: do not edit by hand.
#pragma once

struct CurioJack {
  int cc;            // MIDI CC number, 1 to 112
  int level;         // 0 curiosity, 1 suite, 2 proximity, 3 proximity suite
  const char* label; // the name printed beside the jack
  const char* key;   // the app's automation key (c:music, s:needle-drop...)
};

struct CurioBank {
  const char* slug;
  const char* title;
  int channel;       // MIDI channel, 1 to 16
  int count;         // jacks in use, up to 16
  CurioJack jacks[16];
};

static const int CURIO_BANK_COUNT = ${mods.length};
static const int CURIO_FOCUS_CHANNEL = ${bank.focus.channel};

static const CurioBank CURIO_BANKS[CURIO_BANK_COUNT] = {
${banks.join("\n")}
};
`
);

/* ---------- plugin.hpp / plugin.cpp ---------- */
fs.writeFileSync(
  path.join(OUT, "src", "plugin.hpp"),
  `// Generated by vcv/tools/make-plugin.js.
#pragma once
#include <rack.hpp>

using namespace rack;

extern Plugin* pluginInstance;
extern Model* curioModels[];
extern Model* modelCurioFocus;
extern Model* modelCurioReturn;
`
);
fs.writeFileSync(
  path.join(OUT, "src", "plugin.cpp"),
  `// Generated by vcv/tools/make-plugin.js.
#include "plugin.hpp"
#include "bank.hpp"

Plugin* pluginInstance;

void init(Plugin* p) {
  pluginInstance = p;
  for (int i = 0; i < CURIO_BANK_COUNT; i++)
    p->addModel(curioModels[i]);
  p->addModel(modelCurioFocus);
  p->addModel(modelCurioReturn);
}
`
);

/* ---------- the modules: one generic class, one model per bank ---------- */
fs.writeFileSync(
  path.join(OUT, "src", "Curio.cpp"),
  `// Generated by vcv/tools/make-plugin.js. One generic module; each bank in bank.hpp is its own model.
#include "plugin.hpp"
#include "bank.hpp"

// 0 V is the item's From setting in the app, 10 V its To. Values go out as MIDI CC when they change.
// Every module remembers the MIDI device last chosen on any Curiosities module, so a new one is ready to go.
static json_t* lastMidiJ = NULL;

static const NVGcolor LEVEL_COLORS[4] = {
  nvgRGB(0xc4, 0x47, 0x2f), // curiosity
  nvgRGB(0xc9, 0x8a, 0x14), // suite
  nvgRGB(0x2f, 0x7f, 0x78), // proximity
  nvgRGB(0x5d, 0x4f, 0xa8), // proximity suite
};

// ---------- OSC over UDP to the desktop app's bridge (127.0.0.1:7000), the second way out besides MIDI ----------
// Address /curio/set/<level>/<id> with one float 0..1, as in the desktop bridge (apps/curiosities/desktop/README.md).
#if defined(ARCH_WIN)
  #include <winsock2.h>
  #include <ws2tcpip.h>
  typedef SOCKET curio_socket;
  #define CURIO_BAD_SOCKET INVALID_SOCKET
#else
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <arpa/inet.h>
  #include <unistd.h>
  typedef int curio_socket;
  #define CURIO_BAD_SOCKET (-1)
#endif
#include <cstring>

struct CurioOsc {
  curio_socket sock = CURIO_BAD_SOCKET;
  sockaddr_in addr;

  bool open() {
    if (sock != CURIO_BAD_SOCKET)
      return true;
#if defined(ARCH_WIN)
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif
    sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock == CURIO_BAD_SOCKET)
      return false;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(7000);
    addr.sin_addr.s_addr = htonl(0x7f000001); // 127.0.0.1
    return true;
  }

  static void pad(std::string& b) {
    do b.push_back('\\0'); while (b.size() % 4);
  }

  // One OSC message with one big-endian int32 (",i").
  void sendInt(const std::string& address, int32_t v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",i";
    pad(b);
    uint32_t u = htonl((uint32_t) v);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }

  // One OSC message: the address, the type tag ",f", one big-endian float.
  void sendFloat(const std::string& address, float v) {
    if (!open())
      return;
    std::string b = address;
    pad(b);
    b += ",f";
    pad(b);
    uint32_t u;
    std::memcpy(&u, &v, 4);
    u = htonl(u);
    b.append((const char*) &u, 4);
    sendto(sock, b.data(), (int) b.size(), 0, (const sockaddr*) &addr, sizeof(addr));
  }
};
static CurioOsc curioOsc;

// "c:music" -> "/curio/set/c/music" (or "/curio/trigger/c/music")
static std::string oscAddress(const char* key, const char* verb = "set") {
  std::string k = key;
  size_t colon = k.find(':');
  if (colon == std::string::npos)
    return "";
  return std::string("/curio/") + verb + "/" + k.substr(0, colon) + "/" + k.substr(colon + 1);
}

struct CurioModule : Module {
  const CurioBank* bank;
  midi::Output midiOutput;
  int lastValues[16];
  float lastOsc[16];
  bool useOsc = false; // send OSC to the desktop app instead of MIDI
  bool gateOn[16] = {};
  dsp::ClockDivider sendDivider;
  dsp::ClockDivider rememberDivider;

  CurioModule(const CurioBank* b) : bank(b) {
    config(0, 32, 0, 0);
    for (int i = 0; i < 16; i++) {
      if (i < bank->count) {
        configInput(i, bank->jacks[i].label);
        configInput(16 + i, std::string(bank->jacks[i].label) + ": on/off gate (OSC)");
      }
      else {
        configInput(i, "Unused");
        configInput(16 + i, "Unused");
      }
    }
    sendDivider.setDivision(64);
    rememberDivider.setDivision(48000);
    onReset();
  }

  void onReset() override {
    for (int i = 0; i < 16; i++) {
      lastValues[i] = -1;
      lastOsc[i] = -1.f;
    }
    midiOutput.reset();
    if (lastMidiJ)
      midiOutput.fromJson(lastMidiJ);
    midiOutput.setChannel(bank->channel - 1);
  }

  void process(const ProcessArgs& args) override {
    if (rememberDivider.process()) {
      // Remember this module's device for the next one added.
      if (midiOutput.getDeviceId() >= 0) {
        if (lastMidiJ)
          json_decref(lastMidiJ);
        lastMidiJ = midiOutput.toJson();
      }
    }
    if (!sendDivider.process())
      return;
    if (useOsc && bank->jacks[0].key[0]) {
      // Gates switch the item on and off: /curio/trigger/<level>/<id> 1 on the rise, 0 on the fall.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[16 + i].isConnected())
          continue;
        bool high = inputs[16 + i].getVoltage() >= 1.f;
        if (high == gateOn[i])
          continue;
        gateOn[i] = high;
        curioOsc.sendInt(oscAddress(bank->jacks[i].key, "trigger"), high ? 1 : 0);
      }
      // OSC keeps fine steps: anything that moved by more than about 0.1% goes out.
      for (int i = 0; i < bank->count; i++) {
        if (!inputs[i].isConnected())
          continue;
        float m = clamp(inputs[i].getVoltage() / 10.f, 0.f, 1.f);
        if (std::fabs(m - lastOsc[i]) < 0.001f)
          continue;
        lastOsc[i] = m;
        curioOsc.sendFloat(oscAddress(bank->jacks[i].key), m);
      }
      return;
    }
    for (int i = 0; i < bank->count; i++) {
      if (!inputs[i].isConnected())
        continue;
      int v = (int) clamp(std::round(inputs[i].getVoltage() / 10.f * 127.f), 0.f, 127.f);
      if (v == lastValues[i])
        continue;
      lastValues[i] = v;
      midi::Message m;
      m.setStatus(0xb);
      m.setNote(bank->jacks[i].cc);
      m.setValue(v);
      midiOutput.sendMessage(m);
    }
  }

  json_t* dataToJson() override {
    json_t* rootJ = json_object();
    json_object_set_new(rootJ, "midi", midiOutput.toJson());
    json_object_set_new(rootJ, "osc", json_boolean(useOsc));
    return rootJ;
  }

  void dataFromJson(json_t* rootJ) override {
    json_t* midiJ = json_object_get(rootJ, "midi");
    if (midiJ)
      midiOutput.fromJson(midiJ);
    json_t* oscJ = json_object_get(rootJ, "osc");
    if (oscJ)
      useOsc = json_boolean_value(oscJ);
    // The channel belongs to the bank, whatever a saved patch says.
    midiOutput.setChannel(bank->channel - 1);
  }
};

// A name printed beside a jack, colored by level. SVG text does not render in Rack, so labels are drawn here.
struct CurioLabel : Widget {
  std::string text;
  NVGcolor color = nvgRGB(0x21, 0x1d, 0x1a);
  float fontSize = 9.f;

  void draw(const DrawArgs& args) override {
    std::shared_ptr<window::Font> font = APP->window->loadFont(asset::system("res/fonts/DejaVuSans.ttf"));
    if (!font || font->handle < 0)
      return;
    nvgFontFaceId(args.vg, font->handle);
    nvgFontSize(args.vg, fontSize);
    nvgFillColor(args.vg, color);
    nvgTextAlign(args.vg, NVG_ALIGN_LEFT | NVG_ALIGN_TOP);
    nvgTextLineHeight(args.vg, 1.05f);
    nvgTextBox(args.vg, 0, 0, box.size.x, text.c_str(), NULL);
  }
};

static CurioLabel* makeLabel(Vec pos, Vec size, std::string text, NVGcolor color, float fontSize) {
  CurioLabel* l = new CurioLabel;
  l->box.pos = pos;
  l->box.size = size;
  l->text = text;
  l->color = color;
  l->fontSize = fontSize;
  return l;
}

// Two columns of eight jacks, each with its name to the right.
static void addJacks(ModuleWidget* w, Module* module, const CurioBank* bank, int count, const char* const* names, const int* levels) {
  for (int i = 0; i < 16; i++) {
    int col = i / 8;
    int row = i % 8;
    float x = 6.f + col * 40.f;
    float y = 30.f + row * 12.f;
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, y)), module, i));
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x + 8.5f, y)), module, 16 + i));
    if (i < count)
      w->addChild(makeLabel(mm2px(Vec(x + 13.f, y - 4.2f)), mm2px(Vec(23.f, 9.f)), names[i], LEVEL_COLORS[levels[i]], 8.f));
  }
}

struct CurioWidget : ModuleWidget {
  const CurioBank* bank;

  CurioWidget(CurioModule* module, const CurioBank* b) : bank(b) {
    setModule(module);
    setPanel(createPanel(asset::plugin(pluginInstance, "res/Curio.svg")));
    addChild(makeLabel(mm2px(Vec(4.f, 6.f)), mm2px(Vec(${HP * 5.08 - 8}f, 8.f)), bank->title, nvgRGB(0x21, 0x1d, 0x1a), 14.f));
    addChild(makeLabel(mm2px(Vec(4.f, 14.f)), mm2px(Vec(${HP * 5.08 - 8}f, 8.f)),
      string::f("MIDI ch %d, CC %d-%d. Left jack: 0 V From, 10 V To. Right jack: on/off gate (OSC).", bank->channel, bank->jacks[0].cc, bank->jacks[bank->count - 1].cc),
      nvgRGB(0x6d, 0x65, 0x5d), 8.f));
    const char* names[16];
    int levels[16];
    for (int i = 0; i < 16; i++) {
      names[i] = i < bank->count ? bank->jacks[i].label : "";
      levels[i] = i < bank->count ? bank->jacks[i].level : 0;
    }
    addJacks(this, module, bank, bank->count, names, levels);
  }

  void appendContextMenu(Menu* menu) override {
    CurioModule* module = dynamic_cast<CurioModule*>(this->module);
    if (!module)
      return;
    menu->addChild(new MenuSeparator);
    if (bank->jacks[0].key[0])
      menu->addChild(createBoolPtrMenuItem("Send by OSC to the desktop app (port 7000)", "", &module->useOsc));
    menu->addChild(createMenuLabel("MIDI output (to the Curiosities app in a browser)"));
    appendMidiMenu(menu, &module->midiOutput);
  }
};

// Each bank is its own model: a module and widget type fixed to one entry of CURIO_BANKS.
template <int N>
struct BankModule : CurioModule {
  BankModule() : CurioModule(&CURIO_BANKS[N]) {}
};
template <int N>
struct BankWidget : CurioWidget {
  BankWidget(BankModule<N>* module) : CurioWidget(module, &CURIO_BANKS[N]) {}
};

Model* curioModels[] = {
${mods.map((m, i) => `  createModel<BankModule<${i}>, BankWidget<${i}>>(${cstr(m.slug)}),`).join("\n")}
};

// ---------- Focus: one item's sliders, chosen in the app ----------
static const CurioBank FOCUS_BANK = {
  "Curio-Focus", "Focus", CURIO_FOCUS_CHANNEL, 16, {
    { 1, 0, "The item itself", "" }, { 2, 0, "Slider 2", "" }, { 3, 0, "Slider 3", "" }, { 4, 0, "Slider 4", "" },
    { 5, 0, "Slider 5", "" }, { 6, 0, "Slider 6", "" }, { 7, 0, "Slider 7", "" }, { 8, 0, "Slider 8", "" },
    { 9, 0, "Slider 9", "" }, { 10, 0, "Slider 10", "" }, { 11, 0, "Slider 11", "" }, { 12, 0, "Slider 12", "" },
    { 13, 0, "Slider 13", "" }, { 14, 0, "Slider 14", "" }, { 15, 0, "Slider 15", "" }, { 16, 0, "Slider 16", "" },
  }
};
struct FocusModule : CurioModule {
  FocusModule() : CurioModule(&FOCUS_BANK) {}
};
struct FocusWidget : CurioWidget {
  FocusWidget(FocusModule* module) : CurioWidget(module, &FOCUS_BANK) {
    addChild(makeLabel(mm2px(Vec(4.f, 122.f)), mm2px(Vec(${HP * 5.08 - 8}f, 6.f)), "Pick the item in the app's VCV badge.", nvgRGB(0x6d, 0x65, 0x5d), 8.f));
  }
};
Model* modelCurioFocus = createModel<FocusModule, FocusWidget>("Curio-Focus");

// ---------- Return: values coming back from the desktop app ----------
// The desktop bridge sends /curio/value/<level>/<id> f (0..1) on UDP 7001 about 30 times a second. One socket is
// shared by every Return module; whichever module gets the lock first reads what has arrived.
#include <map>
#include <mutex>
#if !defined(ARCH_WIN)
  #include <fcntl.h>
#endif

struct CurioReceiver {
  std::mutex lock;
  curio_socket sock = CURIO_BAD_SOCKET;
  bool failed = false;
  std::map<std::string, float> values; // "c:music" -> 0..1

  bool open() {
    if (sock != CURIO_BAD_SOCKET)
      return true;
    if (failed)
      return false;
#if defined(ARCH_WIN)
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif
    sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock == CURIO_BAD_SOCKET) {
      failed = true;
      return false;
    }
    int yes = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char*) &yes, sizeof(yes));
#if defined(ARCH_WIN)
    u_long nb = 1;
    ioctlsocket(sock, FIONBIO, &nb);
#else
    fcntl(sock, F_SETFL, fcntl(sock, F_GETFL, 0) | O_NONBLOCK);
#endif
    sockaddr_in a;
    std::memset(&a, 0, sizeof(a));
    a.sin_family = AF_INET;
    a.sin_port = htons(7001);
    a.sin_addr.s_addr = htonl(0x7f000001);
    if (bind(sock, (const sockaddr*) &a, sizeof(a)) != 0) {
      failed = true;
      return false;
    }
    return true;
  }

  static size_t padded(size_t n) {
    return (n + 4) & ~((size_t) 3);
  }

  // One OSC message or bundle element. Only /curio/value/<level>/<id> with a float is kept.
  void parse(const char* d, size_t n) {
    if (n >= 16 && std::memcmp(d, "#bundle", 8) == 0) {
      size_t i = 16;
      while (i + 4 <= n) {
        uint32_t len;
        std::memcpy(&len, d + i, 4);
        len = ntohl(len);
        i += 4;
        if (i + len > n)
          break;
        parse(d + i, len);
        i += len;
      }
      return;
    }
    size_t alen = strnlen(d, n);
    if (alen == n)
      return;
    std::string address(d, alen);
    size_t t = padded(alen);
    if (t + 2 > n || d[t] != ',' || d[t + 1] != 'f')
      return;
    size_t v = t + padded(strnlen(d + t, n - t));
    if (v + 4 > n)
      return;
    const std::string prefix = "/curio/value/";
    if (address.compare(0, prefix.size(), prefix) != 0)
      return;
    std::string rest = address.substr(prefix.size());
    size_t slash = rest.find('/');
    if (slash == std::string::npos)
      return;
    uint32_t u;
    std::memcpy(&u, d + v, 4);
    u = ntohl(u);
    float f;
    std::memcpy(&f, &u, 4);
    values[rest.substr(0, slash) + ":" + rest.substr(slash + 1)] = f;
  }

  void poll() {
    if (!open())
      return;
    char buf[2048];
    for (int k = 0; k < 256; k++) {
      int got = (int) recvfrom(sock, buf, sizeof(buf), 0, NULL, NULL);
      if (got <= 0)
        break;
      parse(buf, (size_t) got);
    }
  }
};
static CurioReceiver curioReceiver;

struct ReturnModule : Module {
  const CurioBank* bank = NULL; // the bank of the module on the left, if it is a Curiosities module
  dsp::ClockDivider divider;
  float out[16] = {};

  ReturnModule() {
    config(0, 0, 16, 0);
    for (int i = 0; i < 16; i++)
      configOutput(i, string::f("Value back from the app %d", i + 1));
    divider.setDivision(256);
  }

  void process(const ProcessArgs& args) override {
    if (divider.process()) {
      CurioModule* left = dynamic_cast<CurioModule*>(leftExpander.module);
      bank = (left && left->bank->jacks[0].key[0]) ? left->bank : NULL;
      if (bank && curioReceiver.lock.try_lock()) {
        curioReceiver.poll();
        for (int i = 0; i < 16; i++) {
          auto it = i < bank->count ? curioReceiver.values.find(bank->jacks[i].key) : curioReceiver.values.end();
          out[i] = it != curioReceiver.values.end() ? clamp(it->second, 0.f, 1.f) * 10.f : 0.f;
        }
        curioReceiver.lock.unlock();
      }
    }
    for (int i = 0; i < 16; i++)
      outputs[i].setVoltage(bank ? out[i] : 0.f);
  }
};

// A label that names the item of the module on the left, so the same Return module works beside any bank.
struct ReturnLabel : CurioLabel {
  ReturnModule* module = NULL;
  int index = 0;
  void draw(const DrawArgs& args) override {
    text = (module && module->bank && index < module->bank->count) ? module->bank->jacks[index].label : "";
    if (index == 0 && !(module && module->bank))
      text = "Place me right of a Curiosities module";
    CurioLabel::draw(args);
  }
};

struct ReturnWidget : ModuleWidget {
  ReturnWidget(ReturnModule* module) {
    setModule(module);
    setPanel(createPanel(asset::plugin(pluginInstance, "res/Curio.svg")));
    addChild(makeLabel(mm2px(Vec(4.f, 6.f)), mm2px(Vec(73.f, 8.f)), "Return", nvgRGB(0x21, 0x1d, 0x1a), 14.f));
    addChild(makeLabel(mm2px(Vec(4.f, 14.f)), mm2px(Vec(73.f, 8.f)), "Values back from the desktop app, 0 to 10 V (OSC on port 7001).", nvgRGB(0x6d, 0x65, 0x5d), 8.f));
    for (int i = 0; i < 16; i++) {
      int col = i / 8;
      int row = i % 8;
      float x = 6.f + col * 40.f;
      float y = 30.f + row * 12.f;
      addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(x, y)), module, i));
      ReturnLabel* l = new ReturnLabel;
      l->box.pos = mm2px(Vec(x + 5.f, y - 4.2f));
      l->box.size = mm2px(Vec(30.f, 9.f));
      l->module = module;
      l->index = i;
      l->fontSize = 8.f;
      addChild(l);
    }
  }
};
Model* modelCurioReturn = createModel<ReturnModule, ReturnWidget>("Curio-Return");
`
);

/* ---------- panel ---------- */
const w = (HP * 5.08).toFixed(2);
fs.writeFileSync(
  path.join(OUT, "res", "Curio.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" width="${w}mm" height="128.5mm" viewBox="0 0 ${w} 128.5">
  <rect width="${w}" height="128.5" fill="#f6f3ee"/>
  <rect y="0" width="${w}" height="2" fill="#c4472f"/>
  <rect x="${(w / 4).toFixed(2)}" y="0" width="${(w / 4).toFixed(2)}" height="2" fill="#c98a14"/>
  <rect x="${(w / 2).toFixed(2)}" y="0" width="${(w / 4).toFixed(2)}" height="2" fill="#2f7f78"/>
  <rect x="${((3 * w) / 4).toFixed(2)}" y="0" width="${(w / 4).toFixed(2)}" height="2" fill="#5d4fa8"/>
  <line x1="${(w / 2).toFixed(2)}" y1="24" x2="${(w / 2).toFixed(2)}" y2="120" stroke="#e2dbd1" stroke-width="0.3"/>
</svg>
`
);

console.log(`${mods.length} modules + Focus + Return written to vcv/plugin/ (${bank.jacks.length} jacks)`);
